mod browser;
mod event;
mod reader;
mod settings;
mod wifi;

use self::event::{AppEvent, EventMode, EventPump};
use self::wifi::{WifiPhase, WifiState};
use crate::browser::{truncate_for_width, FileBrowserState};
use crate::display::{Display, RefreshMode};
use crate::font::{Font, FontSet};
use crate::hardware::Hardware;
use crate::power::PowerManager;
use crate::reader::{ReaderCache, ReaderState};
use anyhow::Result;
use log::{debug, info, warn};

const DEFAULT_LOOP_DELAY_MS: u32 = 5;
const IDLE_LOOP_DELAY_MS: u32 = 50;
const CONTENT_TOP: usize = 12;
const LIST_X: usize = 24;
const LIST_RIGHT_MARGIN: usize = 16;

// Generated by tools/generate_font.py
static FONT_20_DATA: &[u8] = include_bytes!("../../generated/font_20.bin");
static FONT_23_DATA: &[u8] = include_bytes!("../../generated/font_23.bin");
static FONT_14_DATA: &[u8] = include_bytes!("../../generated/font_14.bin");
static FONT_12_DATA: &[u8] = include_bytes!("../../generated/font_12.bin");

#[derive(Clone, Copy, Debug)]
pub(super) enum Activity {
    FileBrowser,
    Reader(ReaderState),
    Settings,
    WifiSettings,
}

impl Activity {
    fn event_mode(self) -> EventMode {
        match self {
            Self::FileBrowser => EventMode::FileBrowser,
            Self::Reader(_) => EventMode::Reader,
            Self::Settings => EventMode::Settings,
            Self::WifiSettings => EventMode::WifiSettings(event::WifiInputMode::Navigate),
        }
    }
}

pub struct ReaderApp {
    hardware: Hardware,
    display: Display,
    ui_font: Font,
    reader_font: Font,
    math_font: Font,
    script_font: Font,
    power: PowerManager,
    event_pump: EventPump,
    md_files: Vec<String>,
    browser_root_dir: String,
    browser: FileBrowserState,
    settings_selected: usize,
    settings_status: String,
    activity: Activity,
    wifi_state: Option<WifiState>,
    reader_cache: Option<ReaderCache>,
    wifi_suspended_for_reader: bool,
    reader_history: Vec<ReaderState>,
}

impl ReaderApp {
    pub fn boot(mut hardware: Hardware, mut display: Display) -> Result<Self> {
        info!("Booting rr_reader");

        hardware.mount_storage()?;
        display.begin()?;

        let ui_font = Font::new(FONT_20_DATA)?;
        let reader_font = Font::new(FONT_23_DATA)?;
        let math_font = Font::new(FONT_14_DATA)?;
        let script_font = Font::new(FONT_12_DATA)?;
        info!(
            "UI font loaded: {}x{}px, {} glyphs",
            ui_font.glyph_width, ui_font.glyph_height, ui_font.glyph_count
        );
        info!(
            "Reader font loaded: {}x{}px, {} glyphs",
            reader_font.glyph_width, reader_font.glyph_height, reader_font.glyph_count
        );
        info!(
            "Math font loaded: {}x{}px, {} glyphs",
            math_font.glyph_width, math_font.glyph_height, math_font.glyph_count
        );
        info!(
            "Script font loaded: {}x{}px, {} glyphs",
            script_font.glyph_width, script_font.glyph_height, script_font.glyph_count
        );

        let md_files = match hardware.storage.list_markdown_files("") {
            Ok(files) => files,
            Err(e) => {
                warn!("Failed to scan vault: {}", e);
                Vec::new()
            }
        };
        info!("Found {} markdown files in vault", md_files.len());

        draw_boot_screen(&mut display, &ui_font, md_files.len());
        display.flush_with_mode(RefreshMode::Full)?;

        info!("Boot phase 1 complete");

        let browser_root_dir = match hardware.storage.read_browser_root_dir() {
            Ok(root) => root,
            Err(e) => {
                warn!("Failed to load browser root config: {}", e);
                String::new()
            }
        };

        let mut app = Self {
            hardware,
            display,
            ui_font,
            reader_font,
            math_font,
            script_font,
            power: PowerManager::new(),
            event_pump: EventPump::new(),
            md_files,
            browser_root_dir,
            browser: FileBrowserState::new_root(),
            settings_selected: 0,
            settings_status: String::new(),
            activity: Activity::FileBrowser,
            wifi_state: None,
            reader_cache: None,
            wifi_suspended_for_reader: false,
            reader_history: Vec::new(),
        };
        app.browser.current_dir = app.browser_root_dir.clone();
        app.reload_browser_entries(None);
        app.render_current_activity();
        app.flush_ui_refresh();
        Ok(app)
    }

    pub fn tick(&mut self) -> Result<()> {
        let mode = if matches!(self.activity, Activity::WifiSettings) {
            let input_mode = match &self.wifi_state {
                Some(state) => match state.phase {
                    WifiPhase::Scanning | WifiPhase::Connecting => event::WifiInputMode::Waiting,
                    WifiPhase::NetworkList
                    | WifiPhase::PasswordChoice
                    | WifiPhase::ConnectResult => event::WifiInputMode::Navigate,
                    WifiPhase::PasswordInput => event::WifiInputMode::PasswordInput,
                },
                None => event::WifiInputMode::Navigate,
            };
            EventMode::WifiSettings(input_mode)
        } else {
            self.activity.event_mode()
        };
        let events = self
            .event_pump
            .poll(&mut self.hardware, &mut self.power, mode);
        for event in events {
            self.handle_event(event)?;
        }

        self.flush_display_if_dirty()?;

        Ok(())
    }

    fn handle_event(&mut self, event: AppEvent) -> Result<()> {
        match event {
            AppEvent::PowerShortPress => self.open_random_file(),
            AppEvent::PowerLongPress => {
                info!("Power long press -> sleep");
                self.power.enter_deep_sleep(None);
            }
            AppEvent::BrowserMove(delta) => self.move_browser_selection(delta),
            AppEvent::BrowserConfirm => self.open_selected_file(),
            AppEvent::BrowserBack => self.handle_browser_back(),
            AppEvent::BrowserOpenSettings => self.open_settings_page(),
            AppEvent::ReaderBack => {
                self.reader_history.clear();
                if let Activity::Reader(reader) = self.activity {
                    self.on_exit_reader_mode();
                    self.activity = Activity::FileBrowser;
                    let selected_path = self.md_files.get(reader.file_index).cloned();
                    self.reload_browser_entries(selected_path.as_deref());
                    self.render_file_browser();
                }
            }
            AppEvent::ReaderMove(delta) => self.move_reader_page(delta),
            AppEvent::ReaderBackHistory => {
                self.navigate_back_in_history();
            }
            AppEvent::ReaderFollowLink => {
                if !self.try_follow_wiki_link() {
                    self.render_current_file();
                }
            }
            AppEvent::ReaderRefresh => {
                self.cycle_wiki_link_selection();
            }
            AppEvent::SettingsMove(delta) => self.move_settings_selection(delta),
            AppEvent::SettingsConfirm => self.confirm_settings_selection(),
            AppEvent::SettingsBack => {
                if matches!(self.activity, Activity::Settings) {
                    self.activity = Activity::FileBrowser;
                    self.reload_browser_entries(None);
                    debug!(
                        "Switched to FileBrowser: md_files={} browser_entries={} current_dir={:?}",
                        self.md_files.len(),
                        self.browser.entries.len(),
                        self.browser.current_dir
                    );
                    self.render_file_browser();
                }
            }
            AppEvent::WifiMove(delta) => self.handle_wifi_move(delta),
            AppEvent::WifiConfirm => self.handle_wifi_confirm(),
            AppEvent::WifiBack => self.handle_wifi_back(),
            AppEvent::WifiCursorMove(delta) => self.handle_wifi_cursor_move(delta),
            AppEvent::WifiCharChange(delta) => self.handle_wifi_char_change(delta),
            AppEvent::IdleTimeout { idle_ticks } => {
                info!("Auto-sleep after {} idle ticks", idle_ticks);
                self.power.enter_deep_sleep(None);
            }
        }

        Ok(())
    }

    fn render_current_activity(&mut self) {
        match self.activity {
            Activity::FileBrowser => self.render_file_browser(),
            Activity::Reader(_) => self.render_current_file(),
            Activity::Settings => self.render_settings_page(),
            Activity::WifiSettings => self.render_wifi_settings_page(),
        }
    }

    fn flush_ui_refresh(&mut self) {
        if let Err(e) = self.flush_display_if_dirty() {
            warn!("Interactive refresh failed: {}", e);
        }
    }

    fn flush_display_if_dirty(&mut self) -> Result<()> {
        let input = &mut self.hardware.input;
        self.display
            .flush_if_dirty_polling(|| input.poll_during_blocking_wait())
    }

    fn bottom_bar_total_height(&self) -> usize {
        self.ui_font.glyph_height as usize + 12
    }

    fn bottom_bar_sep_y(&self) -> usize {
        Display::height() - self.ui_font.glyph_height as usize - 12
    }

    fn bottom_bar_text_y(&self) -> usize {
        Display::height() - self.ui_font.glyph_height as usize - 6
    }

    fn draw_bottom_bar(&mut self, left: &str, right: &str) {
        let sep_y = self.bottom_bar_sep_y();
        let text_y = self.bottom_bar_text_y();
        let bar_width = Display::width() - LIST_X - LIST_RIGHT_MARGIN;
        self.display.fill_rect(LIST_X, sep_y, bar_width, 1, 0x00);
        let max_left = bar_width.saturating_sub(60);
        let left = truncate_for_width(&self.ui_font, left, max_left);
        self.display
            .draw_text_font(&self.ui_font, &left, LIST_X, text_y);
        if !right.is_empty() {
            let right_w = self.ui_font.text_width(right);
            let right_x = (Display::width() - LIST_RIGHT_MARGIN).saturating_sub(right_w);
            self.display
                .draw_text_font(&self.ui_font, right, right_x, text_y);
        }
    }

    pub fn loop_delay_ms(&self) -> u32 {
        if self.event_pump.idle_ticks() > 500 {
            IDLE_LOOP_DELAY_MS
        } else {
            DEFAULT_LOOP_DELAY_MS
        }
    }
}

fn draw_boot_screen(display: &mut Display, ui_font: &Font, _md_count: usize) {
    info!("Drawing boot screen");
    display.clear(0xFF);

    let text = "你好，世界。";
    let text_w = ui_font.text_width(text);
    let text_h = ui_font.glyph_height as usize;
    let x = (Display::width().saturating_sub(text_w)) / 2;
    let y = (Display::height().saturating_sub(text_h)) / 2;

    display.draw_text_font(ui_font, text, x, y);
}
