mod event;

use self::event::{AppEvent, EventMode, EventPump};
use crate::browser::{
    file_browser_parts, resolve_wiki_link_target, sort_browser_entries, truncate_for_width,
    BrowserEntry, FileBrowserState,
};
use crate::display::{Display, RefreshMode};
use crate::font::{Font, FontSet};
use crate::hardware::Hardware;
use crate::power::PowerManager;
use crate::reader::{draw_reader_page, ReaderCache, ReaderState, READER_X};
use crate::sync;
use crate::network::{AccessPointInfo, WifiStatus};
use anyhow::Result;
use esp_idf_svc::wifi::AuthMethod;
use log::{debug, info, warn};
use std::collections::BTreeSet;

const DEFAULT_LOOP_DELAY_MS: u32 = 5;
const IDLE_LOOP_DELAY_MS: u32 = 50;
const CONTENT_TOP: usize = 12;
const LIST_X: usize = 24;
const LIST_RIGHT_MARGIN: usize = 16;
const WIFI_SIGNAL_X_OFFSET: usize = 340;
const WIFI_PASSWORD_CHARS: &str =
    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()-_=+[]{}\\|;:'\",.<>/?`~";

// Generated by tools/generate_font.py
static FONT_20_DATA: &[u8] = include_bytes!("../../generated/font_20.bin");
static FONT_23_DATA: &[u8] = include_bytes!("../../generated/font_23.bin");
static FONT_14_DATA: &[u8] = include_bytes!("../../generated/font_14.bin");
static FONT_12_DATA: &[u8] = include_bytes!("../../generated/font_12.bin");

#[derive(Clone, Debug)]
struct WifiState {
    phase: WifiPhase,
    scanned_aps: Vec<AccessPointInfo>,
    selected_index: usize,
    selected_ap_index: usize,
    password_buf: String,
    cursor_pos: usize,
    status_message: String,
}

impl WifiState {
    fn new() -> Self {
        Self {
            phase: WifiPhase::Scanning,
            scanned_aps: Vec::new(),
            selected_index: 0,
            selected_ap_index: 0,
            password_buf: String::with_capacity(64),
            cursor_pos: 0,
            status_message: String::new(),
        }
    }
}

const WIFI_PRESET_PASSWORDS: &[&str] = &["liuzhaohui123", "88888888"];

#[derive(Clone, Debug)]
enum WifiPhase {
    Scanning,
    NetworkList,
    PasswordChoice,
    PasswordInput,
    Connecting,
    ConnectResult,
}

enum WifiConfirmAction {
    Render,
    Connect(String, String),
}

#[derive(Clone, Copy, Debug)]
enum Activity {
    FileBrowser,
    Reader(ReaderState),
    Settings,
    WifiSettings,
}

impl Activity {
    fn event_mode(self) -> EventMode {
        match self {
            Self::FileBrowser => EventMode::FileBrowser,
            Self::Reader(_) => EventMode::Reader,
            Self::Settings => EventMode::Settings,
            Self::WifiSettings => {
                EventMode::WifiSettings(event::WifiInputMode::Navigate)
            }
        }
    }
}

pub struct ReaderApp {
    hardware: Hardware,
    display: Display,
    ui_font: Font,
    reader_font: Font,
    math_font: Font,
    script_font: Font,
    power: PowerManager,
    event_pump: EventPump,
    md_files: Vec<String>,
    browser_root_dir: String,
    browser: FileBrowserState,
    settings_selected: usize,
    settings_status: String,
    activity: Activity,
    wifi_state: Option<WifiState>,
    reader_cache: Option<ReaderCache>,
    wifi_suspended_for_reader: bool,
    reader_history: Vec<ReaderState>,
}

impl ReaderApp {
    pub fn boot(mut hardware: Hardware, mut display: Display) -> Result<Self> {
        info!("Booting rr_reader");

        hardware.mount_storage()?;
        display.begin()?;

        let ui_font = Font::new(FONT_20_DATA)?;
        let reader_font = Font::new(FONT_23_DATA)?;
        let math_font = Font::new(FONT_14_DATA)?;
        let script_font = Font::new(FONT_12_DATA)?;
        info!(
            "UI font loaded: {}x{}px, {} glyphs",
            ui_font.glyph_width, ui_font.glyph_height, ui_font.glyph_count
        );
        info!(
            "Reader font loaded: {}x{}px, {} glyphs",
            reader_font.glyph_width, reader_font.glyph_height, reader_font.glyph_count
        );
        info!(
            "Math font loaded: {}x{}px, {} glyphs",
            math_font.glyph_width, math_font.glyph_height, math_font.glyph_count
        );
        info!(
            "Script font loaded: {}x{}px, {} glyphs",
            script_font.glyph_width, script_font.glyph_height, script_font.glyph_count
        );

        let md_files = match hardware.storage.list_markdown_files("") {
            Ok(files) => files,
            Err(e) => {
                warn!("Failed to scan vault: {}", e);
                Vec::new()
            }
        };
        info!("Found {} markdown files in vault", md_files.len());

        // Keep boot screen blank
        draw_boot_screen(&mut display, &ui_font, md_files.len());
        display.flush_with_mode(RefreshMode::Full)?;

        info!("Boot phase 1 complete");

        let browser_root_dir = match hardware.storage.read_browser_root_dir() {
            Ok(root) => root,
            Err(e) => {
                warn!("Failed to load browser root config: {}", e);
                String::new()
            }
        };

        let mut app = Self {
            hardware,
            display,
            ui_font,
            reader_font,
            math_font,
            script_font,
            power: PowerManager::new(),
            event_pump: EventPump::new(),
            md_files,
            browser_root_dir,
            browser: FileBrowserState::new_root(),
            settings_selected: 0,
            settings_status: String::new(),
            activity: Activity::FileBrowser,
            wifi_state: None,
            reader_cache: None,
            wifi_suspended_for_reader: false,
            reader_history: Vec::new(),
        };
        app.browser.current_dir = app.browser_root_dir.clone();
        app.reload_browser_entries(None);
        app.render_current_activity();
        app.flush_ui_refresh();
        Ok(app)
    }

    pub fn tick(&mut self) -> Result<()> {
        let mode = if matches!(self.activity, Activity::WifiSettings) {
            let input_mode = match &self.wifi_state {
                Some(state) => match state.phase {
                    WifiPhase::Scanning | WifiPhase::Connecting => {
                        event::WifiInputMode::Waiting
                    }
                    WifiPhase::NetworkList | WifiPhase::PasswordChoice
                    | WifiPhase::ConnectResult => {
                        event::WifiInputMode::Navigate
                    }
                    WifiPhase::PasswordInput => event::WifiInputMode::PasswordInput,
                },
                None => event::WifiInputMode::Navigate,
            };
            EventMode::WifiSettings(input_mode)
        } else {
            self.activity.event_mode()
        };
        let events = self
            .event_pump
            .poll(&mut self.hardware, &mut self.power, mode);
        for event in events {
            self.handle_event(event)?;
        }

        self.flush_display_if_dirty()?;

        Ok(())
    }

    fn open_random_file(&mut self) {
        if self.md_files.is_empty() {
            return;
        }
        let idx = (crate::time::now_ms() as usize) % self.md_files.len();
        self.on_enter_reader_mode();
        self.reader_history.clear();
        self.activity = Activity::Reader(ReaderState {
            file_index: idx,
            page_index: 0,
            wiki_link_selected: None,
        });
        self.render_current_file();
    }

    fn handle_event(&mut self, event: AppEvent) -> Result<()> {
        match event {
            AppEvent::PowerShortPress => self.open_random_file(),
            AppEvent::PowerLongPress => {
                info!("Power long press -> sleep");
                self.power.enter_deep_sleep(None);
            }
            AppEvent::BrowserMove(delta) => self.move_browser_selection(delta),
            AppEvent::BrowserConfirm => self.open_selected_file(),
            AppEvent::BrowserBack => self.handle_browser_back(),
            AppEvent::BrowserOpenSettings => self.open_settings_page(),
            AppEvent::ReaderBack => {
                // Long-press Back: return to file browser, clear history
                self.reader_history.clear();
                if let Activity::Reader(reader) = self.activity {
                    self.on_exit_reader_mode();
                    self.activity = Activity::FileBrowser;
                    let selected_path = self.md_files.get(reader.file_index).cloned();
                    self.reload_browser_entries(selected_path.as_deref());
                    self.render_file_browser();
                }
            }
            AppEvent::ReaderMove(delta) => self.move_reader_page(delta),
            AppEvent::ReaderBackHistory => {
                // Short-press Back: go back in navigation history
                self.navigate_back_in_history();
            }
            AppEvent::ReaderFollowLink => {
                // Short press: follow selected wiki link
                if !self.try_follow_wiki_link() {
                    self.render_current_file();
                }
            }
            AppEvent::ReaderRefresh => {
                // Long press: cycle wiki link selection
                self.cycle_wiki_link_selection();
            }
            AppEvent::SettingsMove(delta) => self.move_settings_selection(delta),
            AppEvent::SettingsConfirm => self.confirm_settings_selection(),
            AppEvent::SettingsBack => {
                if matches!(self.activity, Activity::Settings) {
                    self.activity = Activity::FileBrowser;
                    self.reload_browser_entries(None);
                    debug!(
                        "Switched to FileBrowser: md_files={} browser_entries={} current_dir={:?}",
                        self.md_files.len(),
                        self.browser.entries.len(),
                        self.browser.current_dir
                    );
                    self.render_file_browser();
                }
            }
            AppEvent::WifiMove(delta) => self.handle_wifi_move(delta),
            AppEvent::WifiConfirm => self.handle_wifi_confirm(),
            AppEvent::WifiBack => self.handle_wifi_back(),
            AppEvent::WifiCursorMove(delta) => self.handle_wifi_cursor_move(delta),
            AppEvent::WifiCharChange(delta) => self.handle_wifi_char_change(delta),
            AppEvent::IdleTimeout { idle_ticks } => {
                info!("Auto-sleep after {} idle ticks", idle_ticks);
                self.power.enter_deep_sleep(None);
            }
        }

        Ok(())
    }

    fn render_current_activity(&mut self) {
        match self.activity {
            Activity::FileBrowser => self.render_file_browser(),
            Activity::Reader(_) => self.render_current_file(),
            Activity::Settings => self.render_settings_page(),
            Activity::WifiSettings => self.render_wifi_settings_page(),
        }
    }

    fn browser_is_at_root(&self) -> bool {
        self.browser.current_dir == self.browser_root_dir
    }

    fn absolute_prefix_for_current_dir(&self) -> String {
        if self.browser.current_dir.is_empty() {
            String::new()
        } else {
            format!("{}/", self.browser.current_dir)
        }
    }

    fn reload_browser_entries(&mut self, selected_rel_path: Option<&str>) {
        let current_dir = self.browser.current_dir.clone();
        let root_prefix = if self.browser_root_dir.is_empty() {
            String::new()
        } else {
            format!("{}/", self.browser_root_dir)
        };
        let current_prefix = self.absolute_prefix_for_current_dir();
        let mut dirs: BTreeSet<String> = BTreeSet::new();
        let mut files: Vec<BrowserEntry> = Vec::new();

        for rel in &self.md_files {
            if !root_prefix.is_empty()
                && !(rel == &self.browser_root_dir || rel.starts_with(&root_prefix))
            {
                continue;
            }

            if !current_prefix.is_empty() && !rel.starts_with(&current_prefix) {
                continue;
            }

            let rel_from_dir = if current_dir.is_empty() {
                rel.as_str()
            } else {
                &rel[current_dir.len() + 1..]
            };

            if let Some((child_dir, _)) = rel_from_dir.split_once('/') {
                let child_rel_path = if current_dir.is_empty() {
                    child_dir.to_string()
                } else {
                    format!("{}/{}", current_dir, child_dir)
                };
                dirs.insert(child_rel_path);
            } else {
                files.push(BrowserEntry {
                    rel_path: rel.clone(),
                    is_dir: false,
                });
            }
        }

        let mut entries: Vec<BrowserEntry> = dirs
            .into_iter()
            .map(|rel_path| BrowserEntry {
                rel_path,
                is_dir: true,
            })
            .collect();
        entries.extend(files);
        sort_browser_entries(&mut entries);

        debug!(
            "reload_browser_entries: md_files={} root_prefix={:?} current_dir={:?} entries={} (dirs={} files={})",
            self.md_files.len(),
            root_prefix,
            self.browser.current_dir,
            entries.len(),
            entries.iter().filter(|e| e.is_dir).count(),
            entries.iter().filter(|e| !e.is_dir).count()
        );

        self.browser.entries = entries;
        self.browser.selected = 0;
        self.browser.first_visible = 0;

        if let Some(selected_rel_path) = selected_rel_path {
            if let Some(idx) = self
                .browser
                .entries
                .iter()
                .position(|entry| entry.rel_path == selected_rel_path)
            {
                self.set_browser_selection(idx);
            }
        }
    }

    fn move_browser_selection(&mut self, delta: isize) {
        if !matches!(self.activity, Activity::FileBrowser) || self.browser.entries.is_empty() {
            return;
        }

        let count = self.browser.entries.len();
        let next = (self.browser.selected as isize + delta).rem_euclid(count as isize) as usize;
        self.set_browser_selection(next);
        self.render_file_browser();
    }

    fn set_browser_selection(&mut self, selected: usize) {
        let row_count = self.browser_row_count().max(1);
        self.browser.selected = selected.min(self.browser.entries.len().saturating_sub(1));

        if self.browser.selected < self.browser.first_visible {
            self.browser.first_visible = self.browser.selected;
        } else if self.browser.selected >= self.browser.first_visible + row_count {
            self.browser.first_visible = self.browser.selected + 1 - row_count;
        }
    }

    fn open_selected_file(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }

        let entry = match self.browser.entries.get(self.browser.selected).cloned() {
            Some(entry) => entry,
            None => return,
        };

        if entry.is_dir {
            self.browser.current_dir = entry.rel_path;
            self.reload_browser_entries(None);
            self.render_file_browser();
            return;
        }

        let file_index = match self
            .md_files
            .iter()
            .position(|path| path == &entry.rel_path)
        {
            Some(index) => index,
            None => return,
        };

        self.on_enter_reader_mode();
        self.reader_history.clear();
        self.activity = Activity::Reader(ReaderState {
            file_index,
            page_index: 0,
            wiki_link_selected: None,
        });
        self.render_current_file();
    }

    fn handle_browser_back(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }

        if self.browser_is_at_root() {
            return;
        }

        let child_dir = self.browser.current_dir.clone();
        let parent = self.browser.parent_dir();
        self.browser.current_dir = if parent.len() < self.browser_root_dir.len() {
            self.browser_root_dir.clone()
        } else {
            parent
        };
        self.reload_browser_entries(Some(&child_dir));
        self.render_file_browser();
    }

    fn open_settings_page(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }
        self.settings_selected = 0;
        self.activity = Activity::Settings;
        self.render_settings_page();
    }

    fn on_enter_reader_mode(&mut self) {
        self.reader_cache = None;
        self.display.clear_glyph_cache();
        if !self.wifi_suspended_for_reader {
            self.hardware.suspend_wifi_for_reader();
            self.wifi_suspended_for_reader = true;
        }
    }

    fn on_exit_reader_mode(&mut self) {
        if self.wifi_suspended_for_reader {
            self.hardware.resume_wifi_after_reader();
            self.wifi_suspended_for_reader = false;
        }
    }

    fn move_reader_page(&mut self, delta: isize) {
        let reader = match self.activity {
            Activity::Reader(reader) => reader,
            _ => return,
        };

        if self.ensure_reader_cache(reader.file_index).is_err() {
            return;
        }

        let page_count = self.reader_page_count().max(1);
        let next = if delta.is_negative() {
            reader
                .page_index
                .saturating_sub(delta.unsigned_abs().min(reader.page_index))
        } else {
            reader
                .page_index
                .saturating_add(delta as usize)
                .min(page_count - 1)
        };

        if next == reader.page_index {
            return;
        }

        self.activity = Activity::Reader(ReaderState {
            file_index: reader.file_index,
            page_index: next,
            wiki_link_selected: None,
        });
        self.render_current_file();
    }

    fn flush_ui_refresh(&mut self) {
        if let Err(e) = self.flush_display_if_dirty() {
            warn!("Interactive refresh failed: {}", e);
        }
    }

    fn flush_display_if_dirty(&mut self) -> Result<()> {
        let input = &mut self.hardware.input;
        self.display
            .flush_if_dirty_polling(|| input.poll_during_blocking_wait())
    }

    fn render_file_browser(&mut self) {
        self.display.clear_glyph_cache();
        self.display.clear(0xFF);

        let path_title = if self.browser.current_dir.is_empty() {
            "/".to_string()
        } else {
            format!("/{}", self.browser.current_dir)
        };

        if self.browser.entries.is_empty() {
            self.display.draw_text_wrapped(
                &self.ui_font,
                "此目录为空",
                LIST_X,
                CONTENT_TOP,
                Display::width() - LIST_RIGHT_MARGIN,
                3,
            );
            self.draw_bottom_bar(&path_title, "");
            return;
        }

        let selected = self.browser.selected;
        let first_visible = self.browser.first_visible;

        let row_height = self.browser_row_height();
        let row_count = self.browser_row_count();
        let end = (first_visible + row_count).min(self.browser.entries.len());

        for (row, idx) in (first_visible..end).enumerate() {
            let y = CONTENT_TOP + row * row_height;
            let selected_row = idx == selected;
            if selected_row {
                self.display.fill_rect(12, y, 2, row_height - 6, 0x00);
            }

            let entry = &self.browser.entries[idx];
            let display_name = if entry.is_dir {
                format!("{} /", entry.display_name())
            } else {
                entry.display_name().to_string()
            };

            let name = truncate_for_width(
                &self.ui_font,
                &display_name,
                Display::width() - LIST_X - LIST_RIGHT_MARGIN,
            );
            self.display.draw_text_font(&self.ui_font, &name, LIST_X, y);
        }

        self.draw_bottom_bar(&path_title, "");

        debug!(
            "Rendering file browser: dir='{}' selected {}/{}",
            self.browser.current_dir,
            selected + 1,
            self.browser.entries.len()
        );
    }

    fn settings_option_count(&self) -> usize {
        6
    }

    fn move_settings_selection(&mut self, delta: isize) {
        if !matches!(self.activity, Activity::Settings) {
            return;
        }

        let count = self.settings_option_count();
        self.settings_selected =
            (self.settings_selected as isize + delta).rem_euclid(count as isize) as usize;
        self.render_settings_page();
    }

    fn confirm_settings_selection(&mut self) {
        if !matches!(self.activity, Activity::Settings) {
            return;
        }

        match self.settings_selected {
            0 => self.trigger_manual_sync(),
            1 => self.trigger_delete_notes_and_sync(),
            2 => self.trigger_clear_page_cache(),
            3 => self.trigger_clear_image_cache(),
            4 => self.trigger_cache_all_images(),
            5 => self.enter_wifi_settings(),
            _ => {}
        }
    }

    fn render_sync_status_light(&mut self, status: &str) {
        self.display.clear(0xFF);
        let title = "同步中...";
        let title_w = self.ui_font.text_width(title);
        let title_x = (Display::width() - title_w) / 2;
        let title_y = (Display::height() - self.ui_font.glyph_height as usize) / 2 - 10;
        self.display
            .draw_text_font(&self.ui_font, title, title_x, title_y);
        let status_text = format!("状态: {}", status);
        let status_text = truncate_for_width(&self.ui_font, &status_text, Display::width() - LIST_X - LIST_RIGHT_MARGIN);
        self.draw_bottom_bar(&status_text, "");
    }

    fn trigger_manual_sync(&mut self) {
        // Aggressively release reader-related caches before network sync.
        self.reader_cache = None;
        self.display.clear_glyph_cache();

        let wifi_status = self.hardware.connect_wifi_from_storage();
        info!("{}", wifi_status.boot_line());

        let cfg = self.hardware.storage.read_remotely_save_config();
        let final_status = match cfg {
            Ok(Some(cfg)) => {
                info!(
                    "Sync config loaded: endpoint={} region={} bucket={} prefix={} force_path_style={} source={}",
                    cfg.endpoint,
                    cfg.region,
                    cfg.bucket_name,
                    cfg.remote_prefix,
                    cfg.force_path_style,
                    cfg.source_path
                );

                // Initial status
                self.settings_status = "正在连接...".to_string();
                self.render_sync_status_light("正在连接...");
                self.flush_ui_refresh();
                self.display.clear_glyph_cache();

                match sync::sync_vault_from_s3_config(&cfg, &mut |msg: &str| {
                    self.settings_status = msg.to_string();
                    self.render_sync_status_light(msg);
                    self.flush_ui_refresh();
                    self.display.clear_glyph_cache();
                }) {
                    Ok(report) => {
                        self.md_files = match self.hardware.storage.list_markdown_files("") {
                            Ok(files) => {
                                info!("Rescan after sync: {} files", files.len());
                                files
                            }
                            Err(e) => {
                                warn!("Failed to rescan vault after sync: {}", e);
                                self.md_files.clone()
                            }
                        };
                        self.reload_browser_entries(None);
                        info!("Sync status written to {}", report.status_path);
                        format!(
                            "同步完成：下载 {}，跳过 {}，删除 {}",
                            report.downloaded_files, report.skipped_files, report.deleted_files
                        )
                    }
                    Err(e) => {
                        warn!("Sync failed: {}", e);
                        format!("同步失败: {}", e)
                    }
                }
            }
            Ok(None) => "未找到 remotely-save 配置文件".to_string(),
            Err(e) => {
                warn!("Failed to load remotely-save config: {}", e);
                format!("读取同步配置失败: {}", e)
            }
        };

        self.hardware.shutdown_wifi_after_sync();
        // Aggressively free all caches after sync.
        self.reader_cache = None;
        self.display.clear_glyph_cache();
        self.settings_status = final_status;
        self.render_settings_page();
    }

    fn trigger_delete_notes_and_sync(&mut self) {
        self.reader_cache = None;
        self.display.clear_glyph_cache();

        self.settings_status = "正在删除本地 notes...".to_string();
        self.render_sync_status_light("正在删除本地文件...");
        self.flush_ui_refresh();
        self.display.clear_glyph_cache();

        match self.hardware.storage.delete_synced_notes() {
            Ok(()) => {
                self.md_files.clear();
                self.reload_browser_entries(None);
                self.trigger_manual_sync();
            }
            Err(e) => {
                warn!("Failed to delete local synced notes: {}", e);
                self.settings_status = format!("删除 notes 失败: {}", e);
                self.render_settings_page();
            }
        }
    }

    fn trigger_clear_page_cache(&mut self) {
        self.settings_status = match self.hardware.storage.clear_page_cache() {
            Ok(()) => "页面缓存已清除".to_string(),
            Err(e) => format!("清除缓存失败: {}", e),
        };
        self.render_settings_page();
    }

    fn trigger_clear_image_cache(&mut self) {
        let removed = crate::reader::clear_image_cache();
        self.settings_status = format!("已清除 {} 个图片缓存", removed);
        self.render_settings_page();
    }

    fn trigger_cache_all_images(&mut self) {
        self.reader_cache = None;
        self.display.clear_glyph_cache();
        self.settings_status = "正在缓存图片...".to_string();
        self.render_settings_page();
        self.flush_ui_refresh();

        let cached = crate::reader::cache_all_images(&mut |msg: &str| {
            self.settings_status = msg.to_string();
            self.render_settings_page();
            self.flush_ui_refresh();
            self.display.clear_glyph_cache();
        });
        self.settings_status = format!("图片缓存完成: {} 张", cached);
        self.render_settings_page();
    }

    fn render_settings_page(&mut self) {
        self.display.clear(0xFF);

        let current_root = if self.browser_root_dir.is_empty() {
            "/ (vault 根)".to_string()
        } else {
            format!("/{}", self.browser_root_dir)
        };

        let options = [
            "手动同步（S3）",
            "删除本地文件并重新同步",
            "清除页面缓存",
            "清除图片缓存",
            "缓存所有图片",
            "Wi-Fi 设置",
        ];

        for (i, option) in options.iter().enumerate() {
            let y = CONTENT_TOP + i * (self.ui_font.glyph_height as usize + 10);
            if i == self.settings_selected {
                self.display
                    .fill_rect(12, y, 2, self.ui_font.glyph_height as usize + 4, 0x00);
            }
            self.display
                .draw_text_font(&self.ui_font, option, LIST_X, y);
        }

        let root_line = format!("当前: {}", current_root);
        let right = if self.settings_status.is_empty() {
            String::new()
        } else {
            let status = truncate_for_width(
                &self.ui_font,
                &self.settings_status,
                Display::width() - LIST_X - LIST_RIGHT_MARGIN - self.ui_font.text_width(&root_line) - 12,
            );
            status.to_string()
        };
        self.draw_bottom_bar(&root_line, &right);
    }

    /// Cycle the wiki link selection on the current page.
    /// If no wiki links are present, re-render the page (legacy behavior).
    fn cycle_wiki_link_selection(&mut self) {
        let (file_index, page_index) = match &self.activity {
            Activity::Reader(r) => (r.file_index, r.page_index),
            _ => return,
        };

        let link_count = self
            .reader_cache
            .as_mut()
            .and_then(|c| c.load_page(page_index))
            .map(|p| p.wiki_links.len())
            .unwrap_or(0);

        if link_count == 0 {
            // No wiki links: re-render (original behavior)
            self.render_current_file();
            return;
        }

        let current = match &self.activity {
            Activity::Reader(r) => r.wiki_link_selected,
            _ => None,
        };

        let next = match current {
            None => Some(0),
            Some(i) if i + 1 < link_count => Some(i + 1),
            Some(_) => None, // wrap: last → none (deselect)
        };

        self.activity = Activity::Reader(ReaderState {
            file_index,
            page_index,
            wiki_link_selected: next,
        });
        self.render_current_file();
    }

    /// Navigate back to the previous file in the navigation history.
    fn navigate_back_in_history(&mut self) {
        if let Some(prev_state) = self.reader_history.pop() {
            info!(
                "Navigating back: file {} page {}",
                prev_state.file_index, prev_state.page_index
            );
            self.on_enter_reader_mode();
            self.activity = Activity::Reader(prev_state);
            self.render_current_file();
        } else {
            // No history: return to file browser
            if let Activity::Reader(reader) = self.activity {
                self.on_exit_reader_mode();
                self.activity = Activity::FileBrowser;
                let selected_path = self.md_files.get(reader.file_index).cloned();
                self.reload_browser_entries(selected_path.as_deref());
                self.render_file_browser();
            }
        }
    }

    /// Attempt to follow the currently selected wiki link on the reader page.
    /// Returns true if a link was followed, false otherwise.
    fn try_follow_wiki_link(&mut self) -> bool {
        let (_file_index, page_index, selected) = match &self.activity {
            Activity::Reader(r) => (r.file_index, r.page_index, r.wiki_link_selected),
            _ => return false,
        };

        let selected = match selected {
            Some(i) => i,
            None => {
                // No link selected; try the first one as a fallback
                0
            }
        };

        let page = match self
            .reader_cache
            .as_mut()
            .and_then(|c| c.load_page(page_index))
        {
            Some(p) => p,
            None => return false,
        };

        let link = match page.wiki_links.get(selected) {
            Some(l) => l,
            None => return false,
        };

        let target = link.target.clone();
        info!("Following wiki link: [[{}]]", target);

        match resolve_wiki_link_target(&target, &self.md_files) {
            Some(idx) => {
                // Push current state to history before navigating
                if let Activity::Reader(current) = self.activity {
                    self.reader_history.push(current);
                }
                self.on_enter_reader_mode();
                self.activity = Activity::Reader(ReaderState {
                    file_index: idx,
                    page_index: 0,
                    wiki_link_selected: None,
                });
                self.render_current_file();
                true
            }
            None => {
                info!("Wiki link target not found: [[{}]]", target);
                false
            }
        }
    }

    fn render_current_file(&mut self) {
        self.display.clear(0xFF);

        if self.md_files.is_empty() {
            self.display.draw_text_wrapped(
                &self.ui_font,
                "没有 Markdown 文件\n/sdcard/vault",
                READER_X,
                20,
                Display::width() - READER_X,
                4,
            );
            debug!("No files to render");
            return;
        }

        let reader = match &self.activity {
            Activity::Reader(reader) => Some(*reader),
            _ => None,
        };

        let file_index = match self.activity {
            Activity::Reader(reader) => reader.file_index.min(self.md_files.len() - 1),
            _ => 0,
        };
        let rel_path = self.md_files[file_index].clone();
        match self.ensure_reader_cache(file_index) {
            Ok(()) => {
                let page_count = self.reader_page_count().max(1);
                let page_index = reader
                    .map(|reader| reader.page_index.min(page_count - 1))
                    .unwrap_or(0);
                if let Some(reader) = reader {
                    if page_index != reader.page_index {
                        self.activity = Activity::Reader(ReaderState {
                            file_index,
                            page_index,
                            wiki_link_selected: None,
                        });
                    }
                }

                let fonts = FontSet::new(
                    &self.ui_font,
                    &self.reader_font,
                    &self.math_font,
                    &self.script_font,
                );
                if let Some(cache) = self.reader_cache.as_mut() {
                    cache.load_page(page_index);
                }

                let (_, name) = file_browser_parts(&rel_path);
                let title = format!("[{}] {}", file_index + 1, name);

                let page = self
                    .reader_cache
                    .as_mut()
                    .and_then(|c| c.load_page(page_index));
                if let Some(page) = page {
                    let selected = reader.and_then(|r| r.wiki_link_selected);
                    draw_reader_page(&mut self.display, &fonts, page, selected, |image_path| {
                        self.hardware
                            .storage
                            .resolve_asset_path_relative_to(&rel_path, image_path)
                    });
                }
                let footer = format!("{}/{}", page_index + 1, page_count);
                let title = truncate_for_width(
                    &self.ui_font,
                    &title,
                    Display::width() - LIST_X - LIST_RIGHT_MARGIN - self.ui_font.text_width(&footer) - 12,
                );
                self.draw_bottom_bar(&title, &footer);
                debug!(
                    "Rendering file {}/{} page {}/{}: {}",
                    file_index + 1,
                    self.md_files.len(),
                    page_index + 1,
                    page_count,
                    rel_path
                );
            }
            Err(e) => {
                self.display.draw_text_wrapped(
                    &self.ui_font,
                    &format!("Error reading {}:\n{}", rel_path, e),
                    READER_X,
                    20,
                    Display::width() - READER_X,
                    4,
                );
                warn!("Failed to read {}: {}", rel_path, e);
            }
        }
    }

    fn ensure_reader_cache(&mut self, file_index: usize) -> Result<()> {
        if matches!(
            self.reader_cache,
            Some(ReaderCache {
                file_index: cached,
                ..
            }) if cached == file_index
        ) {
            return Ok(());
        }

        // Free heap before heavy markdown parsing
        self.reader_cache = None;
        self.display.clear_glyph_cache();

        #[cfg(debug_assertions)]
        {
            let free_before = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() };
            info!("Free heap before parsing: {} bytes", free_before);
        }

        let rel_path = &self.md_files[file_index];
        let full_path = format!("/sdcard/vault/{}", rel_path);
        let fonts = FontSet::new(
            &self.ui_font,
            &self.reader_font,
            &self.math_font,
            &self.script_font,
        );

        let cache = crate::reader::ReaderCache::load(file_index, &full_path, &fonts)?;
        self.reader_cache = Some(cache);

        #[cfg(debug_assertions)]
        {
            let free_after = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() };
            let min_free = unsafe { esp_idf_hal::sys::esp_get_minimum_free_heap_size() };
            info!(
                "Free heap after parsing: {} bytes (min ever: {})",
                free_after, min_free
            );
        }

        Ok(())
    }

    fn reader_page_count(&self) -> usize {
        self.reader_cache
            .as_ref()
            .map(|cache| cache.page_count)
            .unwrap_or(0)
    }

    fn browser_row_count(&self) -> usize {
        let row_height = self.browser_row_height();
        let bottom_reserved = self.bottom_bar_total_height();
        (Display::height() - CONTENT_TOP - bottom_reserved) / row_height
    }

    fn browser_row_height(&self) -> usize {
        self.ui_font.glyph_height as usize + 6
    }

    fn bottom_bar_total_height(&self) -> usize {
        self.ui_font.glyph_height as usize + 12
    }

    fn bottom_bar_sep_y(&self) -> usize {
        Display::height() - self.ui_font.glyph_height as usize - 12
    }

    fn bottom_bar_text_y(&self) -> usize {
        Display::height() - self.ui_font.glyph_height as usize - 6
    }

    fn draw_bottom_bar(&mut self, left: &str, right: &str) {
        let sep_y = self.bottom_bar_sep_y();
        let text_y = self.bottom_bar_text_y();
        let bar_width = Display::width() - LIST_X - LIST_RIGHT_MARGIN;
        self.display.fill_rect(LIST_X, sep_y, bar_width, 1, 0x00);
        let max_left = bar_width.saturating_sub(60);
        let left = truncate_for_width(&self.ui_font, left, max_left);
        self.display.draw_text_font(&self.ui_font, &left, LIST_X, text_y);
        if !right.is_empty() {
            let right_w = self.ui_font.text_width(right);
            let right_x = (Display::width() - LIST_RIGHT_MARGIN).saturating_sub(right_w);
            self.display.draw_text_font(&self.ui_font, right, right_x, text_y);
        }
    }

    pub fn loop_delay_ms(&self) -> u32 {
        if self.event_pump.idle_ticks() > 500 {
            IDLE_LOOP_DELAY_MS
        } else {
            DEFAULT_LOOP_DELAY_MS
        }
    }

    // ── WiFi settings ────────────────────────────────────────────────

    fn enter_wifi_settings(&mut self) {
        self.reader_cache = None;
        self.display.clear_glyph_cache();
        self.wifi_state = Some(WifiState::new());
        self.activity = Activity::WifiSettings;

        // Show scanning screen immediately
        self.render_wifi_settings_page();
        self.flush_ui_refresh();

        // Blocking scan
        self.perform_wifi_scan();
    }

    fn leave_wifi_settings(&mut self) {
        self.hardware.disconnect_wifi();
        self.wifi_state = None;
        self.activity = Activity::Settings;
        self.settings_status = String::new();
        self.render_settings_page();
    }

    fn perform_wifi_scan(&mut self) {
        match self.hardware.scan_wifi() {
            Ok(aps) => {
                let count = aps.len();
                if let Some(ref mut state) = self.wifi_state {
                    state.scanned_aps = aps;
                    state.selected_index = 0;
                    state.phase = WifiPhase::NetworkList;
                    state.status_message = format!("已扫描 {} 个网络", count);
                }
            }
            Err(e) => {
                if let Some(ref mut state) = self.wifi_state {
                    state.phase = WifiPhase::ConnectResult;
                    state.status_message = format!("扫描失败: {}", e);
                }
            }
        }
        self.render_wifi_settings_page();
    }

    fn handle_wifi_move(&mut self, delta: isize) {
        let is_empty;
        let has_connect_result;
        {
            let state = match self.wifi_state.as_mut() {
                Some(s) => s,
                None => return,
            };
            match state.phase {
                WifiPhase::NetworkList => {
                    if state.scanned_aps.is_empty() {
                        return;
                    }
                    let count = state.scanned_aps.len();
                    state.selected_index =
                        (state.selected_index as isize + delta).rem_euclid(count as isize)
                            as usize;
                    is_empty = false;
                    has_connect_result = false;
                }
                WifiPhase::PasswordChoice => {
                    let count = WIFI_PRESET_PASSWORDS.len() + 1; // +1 for manual input
                    state.selected_index =
                        (state.selected_index as isize + delta).rem_euclid(count as isize)
                            as usize;
                    is_empty = false;
                    has_connect_result = false;
                }
                WifiPhase::ConnectResult => {
                    state.phase = WifiPhase::NetworkList;
                    is_empty = false;
                    has_connect_result = true;
                }
                _ => return,
            }
        }
        if !is_empty || has_connect_result {
            self.render_wifi_settings_page();
        }
    }

    fn handle_wifi_confirm(&mut self) {
        let action = {
            let state = match self.wifi_state.as_mut() {
                Some(s) => s,
                None => return,
            };

            match state.phase {
                WifiPhase::NetworkList => {
                    if state.scanned_aps.is_empty() {
                        return;
                    }
                    let ap = &state.scanned_aps[state.selected_index];
                    let need_pw = ap.auth_method.is_some()
                        && ap.auth_method != Some(AuthMethod::None);

                    if need_pw {
                        state.selected_ap_index = state.selected_index;
                        state.phase = WifiPhase::PasswordChoice;
                        state.selected_index = 0;
                        WifiConfirmAction::Render
                    } else {
                        WifiConfirmAction::Connect(
                            ap.ssid.to_string(),
                            String::new(),
                        )
                    }
                }
                WifiPhase::PasswordChoice => {
                    let ap_idx = state.selected_ap_index;
                    let ssid = state.scanned_aps[ap_idx].ssid.to_string();
                    if state.selected_index < WIFI_PRESET_PASSWORDS.len() {
                        WifiConfirmAction::Connect(
                            ssid,
                            WIFI_PRESET_PASSWORDS[state.selected_index].to_string(),
                        )
                    } else {
                        // "手动输入"
                        state.password_buf.clear();
                        state.cursor_pos = 0;
                        state.phase = WifiPhase::PasswordInput;
                        WifiConfirmAction::Render
                    }
                }
                WifiPhase::PasswordInput => {
                    let ssid = state
                        .scanned_aps
                        .get(state.selected_ap_index)
                        .map(|ap| ap.ssid.as_str().to_string())
                        .unwrap_or_default();
                    let password = state.password_buf.clone();
                    WifiConfirmAction::Connect(ssid, password)
                }
                WifiPhase::ConnectResult => {
                    state.phase = WifiPhase::NetworkList;
                    WifiConfirmAction::Render
                }
                _ => return,
            }
        };

        match action {
            WifiConfirmAction::Render => self.render_wifi_settings_page(),
            WifiConfirmAction::Connect(ssid, password) => {
                self.start_wifi_connect(&ssid, &password)
            }
        }
    }

    fn handle_wifi_back(&mut self) {
        let action = {
            let state = match self.wifi_state.as_mut() {
                Some(s) => s,
                None => return,
            };

            match state.phase {
                WifiPhase::NetworkList => 1, // Leave WiFi settings
                WifiPhase::PasswordChoice => {
                    state.phase = WifiPhase::NetworkList;
                    2 // Back to network list
                }
                WifiPhase::PasswordInput => {
                    state.password_buf.clear();
                    state.cursor_pos = 0;
                    state.phase = WifiPhase::NetworkList;
                    2 // Re-render
                }
                WifiPhase::ConnectResult => {
                    state.phase = WifiPhase::NetworkList;
                    2 // Re-render
                }
                _ => 0, // No action
            }
        };

        match action {
            1 => self.leave_wifi_settings(),
            2 => self.render_wifi_settings_page(),
            _ => {}
        }
    }

    fn handle_wifi_cursor_move(&mut self, delta: i8) {
        let needs_render = {
            let state = match self.wifi_state.as_mut() {
                Some(s) => s,
                None => return,
            };
            if !matches!(state.phase, WifiPhase::PasswordInput) {
                return;
            }
            if delta < 0 {
                state.cursor_pos = state.cursor_pos.saturating_sub(1);
            } else {
                state.cursor_pos = (state.cursor_pos + 1).min(state.password_buf.len());
            }
            true
        };
        if needs_render {
            self.render_wifi_settings_page();
        }
    }

    fn handle_wifi_char_change(&mut self, delta: i8) {
        let needs_render = {
            let state = match self.wifi_state.as_mut() {
                Some(s) => s,
                None => return,
            };
            if !matches!(state.phase, WifiPhase::PasswordInput) {
                return;
            }

            let chars: Vec<char> = WIFI_PASSWORD_CHARS.chars().collect();
            if chars.is_empty() {
                return;
            }

            if state.cursor_pos > state.password_buf.len() {
                state.cursor_pos = state.password_buf.len();
            }

            if state.cursor_pos == state.password_buf.len() {
                state.password_buf.push(chars[0]);
                state.cursor_pos = state.password_buf.len();
            } else {
                let current_char = state.password_buf.as_bytes()[state.cursor_pos] as char;
                let current_idx = chars.iter().position(|&c| c == current_char).unwrap_or(0);
                let new_idx = (current_idx as isize + delta as isize)
                    .rem_euclid(chars.len() as isize) as usize;
                let new_char = chars[new_idx];
                let end = state.cursor_pos + 1;
                state
                    .password_buf
                    .replace_range(state.cursor_pos..end, &new_char.to_string());
            }
            true
        };
        if needs_render {
            self.render_wifi_settings_page();
        }
    }

    fn start_wifi_connect(&mut self, ssid: &str, password: &str) {
        // Render connecting screen
        if let Some(ref mut state) = self.wifi_state {
            state.phase = WifiPhase::Connecting;
            state.status_message = format!("正在连接 {}...", ssid);
        }
        self.render_wifi_settings_page();
        self.flush_ui_refresh();
        self.display.clear_glyph_cache();

        let status = self
            .hardware
            .connect_wifi_with_credentials(ssid, password);

        if let Some(ref mut state) = self.wifi_state {
            match &status {
                WifiStatus::Connected { ssid: connected_ssid, ip } => {
                    // Persist credentials so S3 sync can use them
                    if !password.is_empty() {
                        if let Err(e) = self
                            .hardware
                            .storage
                            .write_wifi_credentials(connected_ssid, password)
                        {
                            warn!("Failed to save WiFi credentials: {}", e);
                        }
                    }
                    state.phase = WifiPhase::ConnectResult;
                    state.status_message =
                        format!("已连接: {} ({})", connected_ssid, ip);
                }
                WifiStatus::Failed { reason, .. } => {
                    state.phase = WifiPhase::ConnectResult;
                    state.status_message = format!("连接失败: {}", reason);
                }
                WifiStatus::NotConfigured => {
                    state.phase = WifiPhase::ConnectResult;
                    state.status_message = "未配置凭据".to_string();
                }
            }
        }
        self.render_wifi_settings_page();
    }

    // ── WiFi rendering ─────────────────────────────────────────────

    fn render_wifi_settings_page(&mut self) {
        let state = match &self.wifi_state {
            Some(s) => s.clone(),
            None => return,
        };

        match state.phase {
            WifiPhase::Scanning => self.render_wifi_status("正在扫描 WiFi...", ""),
            WifiPhase::Connecting => self.render_wifi_status(&state.status_message, ""),
            WifiPhase::NetworkList => self.render_wifi_network_list(&state),
            WifiPhase::PasswordChoice => self.render_wifi_password_choice(&state),
            WifiPhase::PasswordInput => self.render_wifi_password_input(&state),
            WifiPhase::ConnectResult => {
                self.render_wifi_status(&state.status_message, "任意键继续")
            }
        }
    }

    fn render_wifi_network_list(&mut self, state: &WifiState) {
        self.display.clear(0xFF);

        let row_height = self.ui_font.glyph_height as usize + 10;
        let bottom_reserved = self.bottom_bar_total_height() + 6;
        let visible_rows = (Display::height() - CONTENT_TOP - bottom_reserved) / row_height;

        if state.scanned_aps.is_empty() {
            self.display.draw_text_wrapped(
                &self.ui_font,
                "未发现 WiFi 网络",
                LIST_X,
                CONTENT_TOP,
                Display::width() - LIST_RIGHT_MARGIN,
                3,
            );
        } else {
            let start = state.selected_index.saturating_sub(visible_rows / 2);
            let start = start.min(state.scanned_aps.len().saturating_sub(visible_rows));
            let end = (start + visible_rows).min(state.scanned_aps.len());

            for i in start..end {
                let row = i - start;
                let y = CONTENT_TOP + row * row_height;

                if i == state.selected_index {
                    self.display
                        .fill_rect(12, y, 2, row_height - 4, 0x00);
                }

                let ap = &state.scanned_aps[i];
                let ssid: String = if ap.ssid.is_empty() {
                    "[隐藏网络]".to_string()
                } else {
                    ap.ssid.to_string()
                };
                let ssid = truncate_for_width(
                    &self.ui_font,
                    &ssid,
                    WIFI_SIGNAL_X_OFFSET - LIST_X,
                );
                self.display
                    .draw_text_font(&self.ui_font, &ssid, LIST_X, y);

                self.draw_signal_bars(y, ap.signal_strength);

                let auth_text = match ap.auth_method {
                    None | Some(AuthMethod::None) => "(开放)",
                    _ => "",
                };
                if !auth_text.is_empty() {
                    let auth_x = WIFI_SIGNAL_X_OFFSET + 60;
                    self.display
                        .draw_text_font(&self.ui_font, auth_text, auth_x, y);
                }
            }
        }

        self.draw_bottom_bar(&state.status_message, "");
    }

    fn render_wifi_password_choice(&mut self, state: &WifiState) {
        self.display.clear(0xFF);

        let ap = state
            .scanned_aps
            .get(state.selected_ap_index)
            .map(|ap| ap.ssid.clone())
            .unwrap_or_default();

        let row_height = self.ui_font.glyph_height as usize + 10;

        let options: Vec<String> = WIFI_PRESET_PASSWORDS
            .iter()
            .enumerate()
            .map(|(i, pw)| format!("常用密码 {} ({})", i + 1, pw))
            .chain(std::iter::once("手动输入...".to_string()))
            .collect();

        for (i, option) in options.iter().enumerate() {
            let y = CONTENT_TOP + 4 + i * row_height;
            if i == state.selected_index {
                self.display
                    .fill_rect(12, y, 2, self.ui_font.glyph_height as usize + 4, 0x00);
            }
            let label =
                truncate_for_width(&self.ui_font, option, Display::width() - LIST_X - LIST_RIGHT_MARGIN);
            self.display.draw_text_font(&self.ui_font, &label, LIST_X, y);
        }

        let bottom_label = format!("选择密码: {}", ap);
        self.draw_bottom_bar(&bottom_label, "");
    }

    fn render_wifi_password_input(&mut self, state: &WifiState) {
        self.display.clear(0xFF);

        let ap = state
            .scanned_aps
            .get(state.selected_ap_index)
            .map(|ap| ap.ssid.clone())
            .unwrap_or_default();

        let input_y = CONTENT_TOP + 12;

        // Render password characters with cursor highlight
        let max_display = 20; // max chars to show on screen
        let chars: Vec<char> = state.password_buf.chars().collect();
        let start = if chars.len() <= max_display {
            0
        } else {
            state.cursor_pos.saturating_sub(max_display / 2)
        };
        let start = start.min(chars.len().saturating_sub(max_display));
        let end = (start + max_display).min(chars.len());

        let cursor_x = LIST_X + 8; // indent
        let char_w = self.ui_font.glyph_width as usize;

        // Draw leading bracket
        self.display
            .draw_text_font(&self.ui_font, "[", LIST_X, input_y);

        // Draw visible characters
        for i in start..end {
            let x = cursor_x + (i - start) * (char_w + 2);
            let ch_str: String = if i < chars.len() {
                chars[i].to_string()
            } else {
                " ".to_string()
            };
            self.display.draw_text_font(&self.ui_font, &ch_str, x, input_y);

            if i == state.cursor_pos {
                // Underline cursor
                self.display.fill_rect(
                    x,
                    input_y + self.ui_font.glyph_height as usize + 1,
                    char_w,
                    2,
                    0x00,
                );
            }
        }

        // Draw trailing bracket and empty slots indicator
        let after_x = cursor_x + (end - start) * (char_w + 2);
        let remaining = state.password_buf.len().saturating_sub(end);
        if remaining > 0 {
            let dots = format!("...]");
            self.display
                .draw_text_font(&self.ui_font, &dots, after_x, input_y);
        } else if state.cursor_pos == state.password_buf.len() && state.password_buf.len() < 64 {
            // Show cursor underline at append position
            let cursor_end_x = cursor_x + (chars.len() - start) * (char_w + 2);
            self.display.fill_rect(
                cursor_end_x,
                input_y + self.ui_font.glyph_height as usize + 1,
                char_w,
                2,
                0x00,
            );
            let close_x = cursor_end_x + char_w + 2;
            self.display
                .draw_text_font(&self.ui_font, "]", close_x, input_y);
        } else {
            let close_x = after_x;
            if state.cursor_pos == state.password_buf.len() && state.password_buf.len() >= 64 {
                // Cursor at end but buffer full
                self.display.fill_rect(
                    close_x,
                    input_y + self.ui_font.glyph_height as usize + 1,
                    char_w,
                    2,
                    0x00,
                );
            }
            self.display
                .draw_text_font(&self.ui_font, "]", close_x, input_y);
        }

        // Character set preview row
        let preview_y = input_y + self.ui_font.glyph_height as usize + 16;
        self.display.fill_rect(
            LIST_X,
            preview_y - 4,
            Display::width() - LIST_X - LIST_RIGHT_MARGIN,
            1,
            0x00,
        );

        // Determine the current character being edited at cursor position
        let current_char = if state.cursor_pos < chars.len() {
            chars[state.cursor_pos]
        } else {
            '0' // appending: first char in charset (same as what Down would insert)
        };

        let charset: Vec<char> = WIFI_PASSWORD_CHARS.chars().collect();
        let current_idx = charset
            .iter()
            .position(|&c| c == current_char)
            .unwrap_or(0);

        // Show a window of charset centered on current character
        let preview_window = 18;
        let half = preview_window / 2;
        let cs_start = if charset.len() <= preview_window {
            0
        } else {
            current_idx.saturating_sub(half).min(charset.len() - preview_window)
        };
        let cs_end = (cs_start + preview_window).min(charset.len());

        let mut preview_str = String::with_capacity(64);
        for (i, &c) in charset[cs_start..cs_end].iter().enumerate() {
            let global_idx = cs_start + i;
            if global_idx == current_idx {
                preview_str.push('[');
                preview_str.push(c);
                preview_str.push(']');
            } else {
                preview_str.push(' ');
                preview_str.push(c);
                preview_str.push(' ');
            }
        }

        let preview_label = "字符: ";
        self.display
            .draw_text_font(&self.ui_font, preview_label, LIST_X, preview_y);
        let label_w = self.ui_font.text_width(preview_label);
        self.display
            .draw_text_font(&self.ui_font, &preview_str, LIST_X + label_w, preview_y);

        // Help text (condensed, placed above bottom bar)
        let help_y = preview_y + self.ui_font.glyph_height as usize + 8;
        self.display.draw_text_wrapped(
            &self.ui_font,
            "上下切换字符  左右移动光标  确认连接  返回取消",
            LIST_X,
            help_y,
            Display::width() - LIST_RIGHT_MARGIN,
            4,
        );

        let bottom_label = format!("连接到: {}", ap);
        self.draw_bottom_bar(&bottom_label, "");
    }

    fn render_wifi_status(&mut self, message: &str, hint: &str) {
        self.display.clear(0xFF);

        let msg_y = Display::height() / 2 - self.ui_font.glyph_height as usize;
        let msg = truncate_for_width(&self.ui_font, message, Display::width() - 2 * LIST_X);
        let msg_w = self.ui_font.text_width(&msg);
        let msg_x = (Display::width() - msg_w) / 2;
        self.display.draw_text_font(&self.ui_font, &msg, msg_x, msg_y);

        self.draw_bottom_bar(hint, "");
    }

    fn draw_signal_bars(&mut self, y: usize, signal_strength: i8) {
        // Convert dBm to bar count: >= -50 → 4, >= -65 → 3, >= -80 → 2, else → 1
        let bars = if signal_strength >= -50 {
            4
        } else if signal_strength >= -65 {
            3
        } else if signal_strength >= -80 {
            2
        } else {
            1
        };

        let bar_h = 4;
        let bar_w = 4;
        let bar_gap = 2;
        let base_y = y + self.ui_font.glyph_height as usize - 4;

        for i in 0..4 {
            let bx = WIFI_SIGNAL_X_OFFSET + i * (bar_w + bar_gap);
            let bh = bar_h * (i + 1);
            let by = base_y - bh;
            if i < bars {
                self.display.fill_rect(bx, by, bar_w, bh, 0x00);
            } else {
                // Outline for empty bars
                self.display.fill_rect(bx, by, bar_w, 1, 0x00);
                self.display.fill_rect(bx, by, 1, bh, 0x00);
                self.display.fill_rect(bx + bar_w - 1, by, 1, bh, 0x00);
                self.display.fill_rect(bx, by + bh - 1, bar_w, 1, 0x00);
            }
        }
    }
}

fn draw_boot_screen(display: &mut Display, ui_font: &Font, _md_count: usize) {
    info!("Drawing boot screen");
    display.clear(0xFF);

    let text = "你好，世界。";
    let text_w = ui_font.text_width(text);
    let text_h = ui_font.glyph_height as usize;
    let x = (Display::width().saturating_sub(text_w)) / 2;
    let y = (Display::height().saturating_sub(text_h)) / 2;

    display.draw_text_font(ui_font, text, x, y);
}
