mod event;

use self::event::{AppEvent, EventMode, EventPump};
use crate::browser::{
    file_browser_parts, sort_browser_entries, truncate_for_width, BrowserEntry, FileBrowserState,
};
use crate::display::{Display, RefreshMode};
use crate::font::{Font, FontSet};
use crate::hardware::Hardware;
use crate::power::PowerManager;
use crate::reader::{
    draw_reader_page, markdown_blocks_and_pages, ReaderCache, ReaderPage, ReaderState,
    PAGE_CACHE_SIZE_MAX, PAGE_CACHE_SIZE_MIN, READER_X,
};
use crate::sync;
use anyhow::Result;
use log::{debug, info, warn};
use std::collections::BTreeMap;

const DEFAULT_LOOP_DELAY_MS: u32 = 5;
const IDLE_LOOP_DELAY_MS: u32 = 50;
const LIST_TOP_Y: usize = 28;
const LIST_BOTTOM_MARGIN: usize = 36;
const LIST_X: usize = 48;
const LIST_RIGHT_MARGIN: usize = 24;
const PAGE_PATH_Y_OFFSET: usize = 34;

// Generated by tools/generate_font.py
static FONT_16_DATA: &[u8] = include_bytes!("../../generated/font_16.bin");
static FONT_18_DATA: &[u8] = include_bytes!("../../generated/font_18.bin");
static FONT_12_DATA: &[u8] = include_bytes!("../../generated/font_12.bin");
static FONT_10_DATA: &[u8] = include_bytes!("../../generated/font_10.bin");

#[derive(Clone, Copy, Debug)]
enum Activity {
    FileBrowser,
    Reader(ReaderState),
    Settings,
}

impl Activity {
    fn event_mode(self) -> EventMode {
        match self {
            Self::FileBrowser => EventMode::FileBrowser,
            Self::Reader(_) => EventMode::Reader,
            Self::Settings => EventMode::Settings,
        }
    }
}

pub struct ReaderApp {
    hardware: Hardware,
    display: Display,
    ui_font: Font,
    reader_font: Font,
    math_font: Font,
    script_font: Font,
    power: PowerManager,
    event_pump: EventPump,
    md_files: Vec<String>,
    browser_root_dir: String,
    browser: FileBrowserState,
    settings_selected: usize,
    settings_status: String,
    activity: Activity,
    reader_cache: Option<ReaderCache>,
    wifi_suspended_for_reader: bool,
}

impl ReaderApp {
    pub fn boot(mut hardware: Hardware, mut display: Display) -> Result<Self> {
        info!("Booting rr_reader");

        hardware.mount_storage()?;
        display.begin()?;

        let ui_font = Font::new(FONT_16_DATA)?;
        let reader_font = Font::new(FONT_18_DATA)?;
        let math_font = Font::new(FONT_12_DATA)?;
        let script_font = Font::new(FONT_10_DATA)?;
        info!(
            "UI font loaded: {}x{}px, {} glyphs",
            ui_font.glyph_width, ui_font.glyph_height, ui_font.glyph_count
        );
        info!(
            "Reader font loaded: {}x{}px, {} glyphs",
            reader_font.glyph_width, reader_font.glyph_height, reader_font.glyph_count
        );
        info!(
            "Math font loaded: {}x{}px, {} glyphs",
            math_font.glyph_width, math_font.glyph_height, math_font.glyph_count
        );
        info!(
            "Script font loaded: {}x{}px, {} glyphs",
            script_font.glyph_width, script_font.glyph_height, script_font.glyph_count
        );

        let md_files = match hardware.storage.list_markdown_files("") {
            Ok(files) => files,
            Err(e) => {
                warn!("Failed to scan vault: {}", e);
                Vec::new()
            }
        };
        info!("Found {} markdown files in vault", md_files.len());

        // Keep boot screen blank
        draw_boot_screen(&mut display, &ui_font, md_files.len());
        display.flush_with_mode(RefreshMode::Full)?;

        info!("Boot phase 1 complete");

        let browser_root_dir = match hardware.storage.read_browser_root_dir() {
            Ok(root) => root,
            Err(e) => {
                warn!("Failed to load browser root config: {}", e);
                String::new()
            }
        };

        let mut app = Self {
            hardware,
            display,
            ui_font,
            reader_font,
            math_font,
            script_font,
            power: PowerManager::new(),
            event_pump: EventPump::new(),
            md_files,
            browser_root_dir,
            browser: FileBrowserState::new_root(),
            settings_selected: 0,
            settings_status: String::new(),
            activity: Activity::FileBrowser,
            reader_cache: None,
            wifi_suspended_for_reader: false,
        };
        app.browser.current_dir = app.browser_root_dir.clone();
        app.reload_browser_entries(None);
        app.render_current_activity();
        app.flush_ui_refresh();
        Ok(app)
    }

    pub fn tick(&mut self) -> Result<()> {
        let mode = self.activity.event_mode();
        let events = self
            .event_pump
            .poll(&mut self.hardware, &mut self.power, mode);
        for event in events {
            self.handle_event(event)?;
        }

        self.flush_display_if_dirty()?;

        Ok(())
    }

    fn handle_event(&mut self, event: AppEvent) -> Result<()> {
        match event {
            AppEvent::PowerLongPress => {
                info!("Power long press -> sleep");
                self.power.enter_deep_sleep(None);
            }
            AppEvent::BrowserMove(delta) => self.move_browser_selection(delta),
            AppEvent::BrowserConfirm => self.open_selected_file(),
            AppEvent::BrowserBack => self.handle_browser_back(),
            AppEvent::BrowserOpenSettings => self.open_settings_page(),
            AppEvent::ReaderBack => {
                if let Activity::Reader(reader) = self.activity {
                    self.on_exit_reader_mode();
                    self.activity = Activity::FileBrowser;
                    let selected_path = self.md_files.get(reader.file_index).cloned();
                    self.reload_browser_entries(selected_path.as_deref());
                    self.render_file_browser();
                }
            }
            AppEvent::ReaderMove(delta) => self.move_reader_page(delta),
            AppEvent::ReaderRefresh => self.render_current_file(),
            AppEvent::SettingsMove(delta) => self.move_settings_selection(delta),
            AppEvent::SettingsConfirm => self.confirm_settings_selection(),
            AppEvent::SettingsBack => {
                if matches!(self.activity, Activity::Settings) {
                    self.activity = Activity::FileBrowser;
                    self.render_file_browser();
                }
            }
            AppEvent::IdleTimeout { idle_ticks } => {
                info!("Auto-sleep after {} idle ticks", idle_ticks);
                self.power.enter_deep_sleep(None);
            }
        }

        Ok(())
    }

    fn render_current_activity(&mut self) {
        match self.activity {
            Activity::FileBrowser => self.render_file_browser(),
            Activity::Reader(_) => self.render_current_file(),
            Activity::Settings => self.render_settings_page(),
        }
    }

    fn browser_is_at_root(&self) -> bool {
        self.browser.current_dir == self.browser_root_dir
    }

    fn absolute_prefix_for_current_dir(&self) -> String {
        if self.browser.current_dir.is_empty() {
            String::new()
        } else {
            format!("{}/", self.browser.current_dir)
        }
    }

    fn reload_browser_entries(&mut self, selected_rel_path: Option<&str>) {
        let current_dir = self.browser.current_dir.clone();
        let root_prefix = if self.browser_root_dir.is_empty() {
            String::new()
        } else {
            format!("{}/", self.browser_root_dir)
        };
        let current_prefix = self.absolute_prefix_for_current_dir();
        let mut dirs: BTreeMap<String, String> = BTreeMap::new();
        let mut files: Vec<BrowserEntry> = Vec::new();

        for rel in &self.md_files {
            if !root_prefix.is_empty()
                && !(rel == &self.browser_root_dir || rel.starts_with(&root_prefix))
            {
                continue;
            }

            if !current_prefix.is_empty() && !rel.starts_with(&current_prefix) {
                continue;
            }

            let rel_from_dir = if current_dir.is_empty() {
                rel.as_str()
            } else {
                &rel[current_dir.len() + 1..]
            };

            if let Some((child_dir, _)) = rel_from_dir.split_once('/') {
                let child_rel_path = if current_dir.is_empty() {
                    child_dir.to_string()
                } else {
                    format!("{}/{}", current_dir, child_dir)
                };
                dirs.entry(child_rel_path)
                    .or_insert_with(|| child_dir.to_string());
            } else {
                let (_, name) = file_browser_parts(rel_from_dir);
                files.push(BrowserEntry {
                    rel_path: rel.clone(),
                    name: name.to_string(),
                    is_dir: false,
                });
            }
        }

        let mut entries: Vec<BrowserEntry> = dirs
            .into_iter()
            .map(|(rel_path, name)| BrowserEntry {
                rel_path,
                name,
                is_dir: true,
            })
            .collect();
        entries.extend(files);
        sort_browser_entries(&mut entries);

        self.browser.entries = entries;
        self.browser.selected = 0;
        self.browser.first_visible = 0;

        if let Some(selected_rel_path) = selected_rel_path {
            if let Some(idx) = self
                .browser
                .entries
                .iter()
                .position(|entry| entry.rel_path == selected_rel_path)
            {
                self.set_browser_selection(idx);
            }
        }
    }

    fn move_browser_selection(&mut self, delta: isize) {
        if !matches!(self.activity, Activity::FileBrowser) || self.browser.entries.is_empty() {
            return;
        }

        let count = self.browser.entries.len();
        let next = (self.browser.selected as isize + delta).rem_euclid(count as isize) as usize;
        self.set_browser_selection(next);
        self.render_file_browser();
    }

    fn set_browser_selection(&mut self, selected: usize) {
        let row_count = self.browser_row_count().max(1);
        self.browser.selected = selected.min(self.browser.entries.len().saturating_sub(1));

        if self.browser.selected < self.browser.first_visible {
            self.browser.first_visible = self.browser.selected;
        } else if self.browser.selected >= self.browser.first_visible + row_count {
            self.browser.first_visible = self.browser.selected + 1 - row_count;
        }
    }

    fn open_selected_file(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }

        let entry = match self.browser.entries.get(self.browser.selected).cloned() {
            Some(entry) => entry,
            None => return,
        };

        if entry.is_dir {
            self.browser.current_dir = entry.rel_path;
            self.reload_browser_entries(None);
            self.render_file_browser();
            return;
        }

        let file_index = match self
            .md_files
            .iter()
            .position(|path| path == &entry.rel_path)
        {
            Some(index) => index,
            None => return,
        };

        self.on_enter_reader_mode();
        self.activity = Activity::Reader(ReaderState {
            file_index,
            page_index: 0,
        });
        self.render_current_file();
    }

    fn handle_browser_back(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }

        if self.browser_is_at_root() {
            return;
        }

        let child_dir = self.browser.current_dir.clone();
        let parent = self.browser.parent_dir();
        self.browser.current_dir = if parent.len() < self.browser_root_dir.len() {
            self.browser_root_dir.clone()
        } else {
            parent
        };
        self.reload_browser_entries(Some(&child_dir));
        self.render_file_browser();
    }

    fn open_settings_page(&mut self) {
        if !matches!(self.activity, Activity::FileBrowser) {
            return;
        }
        self.settings_selected = 0;
        self.activity = Activity::Settings;
        self.render_settings_page();
    }

    fn on_enter_reader_mode(&mut self) {
        if !self.wifi_suspended_for_reader {
            self.hardware.suspend_wifi_for_reader();
            self.wifi_suspended_for_reader = true;
        }
    }

    fn on_exit_reader_mode(&mut self) {
        if self.wifi_suspended_for_reader {
            self.hardware.resume_wifi_after_reader();
            self.wifi_suspended_for_reader = false;
        }
    }

    fn move_reader_page(&mut self, delta: isize) {
        let reader = match self.activity {
            Activity::Reader(reader) => reader,
            _ => return,
        };

        if self.ensure_reader_cache(reader.file_index).is_err() {
            return;
        }

        let page_count = self.reader_page_count().max(1);
        let next = if delta.is_negative() {
            reader
                .page_index
                .saturating_sub(delta.unsigned_abs().min(reader.page_index))
        } else {
            reader
                .page_index
                .saturating_add(delta as usize)
                .min(page_count - 1)
        };

        if next == reader.page_index {
            return;
        }

        self.activity = Activity::Reader(ReaderState {
            file_index: reader.file_index,
            page_index: next,
        });
        self.render_current_file();
    }

    fn flush_ui_refresh(&mut self) {
        if let Err(e) = self.flush_display_if_dirty() {
            warn!("Interactive refresh failed: {}", e);
        }
    }

    fn flush_display_if_dirty(&mut self) -> Result<()> {
        let input = &mut self.hardware.input;
        self.display
            .flush_if_dirty_polling(|| input.poll_during_blocking_wait())
    }

    fn render_file_browser(&mut self) {
        self.display.clear(0xFF);

        if self.browser.entries.is_empty() {
            self.display.draw_text_wrapped(
                &self.ui_font,
                "此目录为空",
                LIST_X,
                LIST_TOP_Y,
                Display::width() - LIST_RIGHT_MARGIN,
                3,
            );

            let path_title = if self.browser.current_dir.is_empty() {
                "/".to_string()
            } else {
                format!("/{}", self.browser.current_dir)
            };
            let path_title = truncate_for_width(&self.ui_font, &path_title, Display::width() - 48);
            self.display.draw_text_font(
                &self.ui_font,
                &path_title,
                LIST_X,
                Display::height() - self.ui_font.glyph_height as usize - PAGE_PATH_Y_OFFSET,
            );
            return;
        }

        let selected = self.browser.selected;
        let first_visible = self.browser.first_visible;

        let row_height = self.browser_row_height();
        let row_count = self.browser_row_count();
        let end = (first_visible + row_count).min(self.browser.entries.len());

        for (row, idx) in (first_visible..end).enumerate() {
            let y = LIST_TOP_Y + row * row_height;
            let selected_row = idx == selected;
            if selected_row {
                self.display.fill_rect(30, y - 2, 2, row_height - 10, 0x00);
            }

            let entry = &self.browser.entries[idx];
            let display_name = if entry.is_dir {
                format!("{} /", entry.name)
            } else {
                entry.name.clone()
            };

            let name = truncate_for_width(
                &self.ui_font,
                &display_name,
                Display::width() - LIST_X - LIST_RIGHT_MARGIN,
            );
            self.display.draw_text_font(&self.ui_font, &name, LIST_X, y);
        }

        let path_title = if self.browser.current_dir.is_empty() {
            "/".to_string()
        } else {
            format!("/{}", self.browser.current_dir)
        };
        let path_title = truncate_for_width(&self.ui_font, &path_title, Display::width() - 48);
        self.display.draw_text_font(
            &self.ui_font,
            &path_title,
            LIST_X,
            Display::height() - self.ui_font.glyph_height as usize - PAGE_PATH_Y_OFFSET,
        );

        debug!(
            "Rendering file browser: dir='{}' selected {}/{}",
            self.browser.current_dir,
            selected + 1,
            self.browser.entries.len()
        );
    }

    fn settings_option_count(&self) -> usize {
        3
    }

    fn move_settings_selection(&mut self, delta: isize) {
        if !matches!(self.activity, Activity::Settings) {
            return;
        }

        let count = self.settings_option_count();
        self.settings_selected =
            (self.settings_selected as isize + delta).rem_euclid(count as isize) as usize;
        self.render_settings_page();
    }

    fn confirm_settings_selection(&mut self) {
        if !matches!(self.activity, Activity::Settings) {
            return;
        }

        match self.settings_selected {
            0 => self.apply_selected_dir_as_browser_root(),
            1 => {
                self.browser_root_dir.clear();
                self.browser.current_dir.clear();
                let _ = self.hardware.storage.write_browser_root_dir("");
                self.settings_status = "已重置文件根目录".to_string();
                self.reload_browser_entries(None);
                self.render_settings_page();
            }
            2 => self.trigger_manual_sync(),
            _ => {}
        }
    }

    fn trigger_manual_sync(&mut self) {
        // Aggressively release reader-related caches before network sync.
        self.reader_cache = None;
        self.display.clear_glyph_cache();

        let wifi_status = self.hardware.connect_wifi_from_storage();
        info!("{}", wifi_status.boot_line());

        let cfg = self.hardware.storage.read_remotely_save_config();
        let final_status = match cfg {
            Ok(Some(cfg)) => {
                info!(
                    "Sync config loaded: endpoint={} region={} bucket={} prefix={} force_path_style={} source={}",
                    cfg.endpoint,
                    cfg.region,
                    cfg.bucket_name,
                    cfg.remote_prefix,
                    cfg.force_path_style,
                    cfg.source_path
                );

                // Initial status
                self.settings_status = "正在连接...".to_string();
                self.render_settings_page();
                self.flush_ui_refresh();

                match sync::sync_vault_from_s3_config(&cfg, &mut |msg: &str| {
                    self.settings_status = msg.to_string();
                    self.render_settings_page();
                    self.flush_ui_refresh();
                }) {
                    Ok(report) => {
                        self.md_files = match self.hardware.storage.list_markdown_files("") {
                            Ok(files) => files,
                            Err(e) => {
                                warn!("Failed to rescan vault after sync: {}", e);
                                self.md_files.clone()
                            }
                        };
                        self.reload_browser_entries(None);
                        info!("Sync status written to {}", report.status_path);
                        format!(
                            "同步完成：下载 {}，跳过 {}，删除 {}",
                            report.downloaded_files, report.skipped_files, report.deleted_files
                        )
                    }
                    Err(e) => {
                        warn!("Sync failed: {}", e);
                        format!("同步失败: {}", e)
                    }
                }
            }
            Ok(None) => "未找到 remotely-save 配置文件".to_string(),
            Err(e) => {
                warn!("Failed to load remotely-save config: {}", e);
                format!("读取同步配置失败: {}", e)
            }
        };

        self.hardware.shutdown_wifi_after_sync();
        self.settings_status = final_status;
        self.render_settings_page();
    }

    fn apply_selected_dir_as_browser_root(&mut self) {
        let selected = match self.browser.entries.get(self.browser.selected) {
            Some(entry) if entry.is_dir => entry.rel_path.clone(),
            _ => self.browser.current_dir.clone(),
        };

        self.browser_root_dir = selected.clone();
        self.browser.current_dir = selected;
        if let Err(e) = self
            .hardware
            .storage
            .write_browser_root_dir(&self.browser_root_dir)
        {
            warn!("Failed to persist browser root dir: {}", e);
        }
        self.reload_browser_entries(None);
        self.render_settings_page();
    }

    fn render_settings_page(&mut self) {
        self.display.clear(0xFF);

        let current_root = if self.browser_root_dir.is_empty() {
            "/ (vault 根)".to_string()
        } else {
            format!("/{}", self.browser_root_dir)
        };

        let options = [
            "将当前目录设为文件根目录",
            "重置文件根目录为 vault 根",
            "手动同步 vault（S3）",
        ];

        for (i, option) in options.iter().enumerate() {
            let y = LIST_TOP_Y + i * (self.ui_font.glyph_height as usize + 18);
            if i == self.settings_selected {
                self.display
                    .fill_rect(30, y - 2, 2, self.ui_font.glyph_height as usize + 4, 0x00);
            }
            self.display
                .draw_text_font(&self.ui_font, option, LIST_X, y);
        }

        let root_line = format!("当前根目录: {}", current_root);
        let root_line = truncate_for_width(&self.ui_font, &root_line, Display::width() - 48);
        self.display.draw_text_font(
            &self.ui_font,
            &root_line,
            LIST_X,
            Display::height() - self.ui_font.glyph_height as usize - PAGE_PATH_Y_OFFSET - 20,
        );

        if !self.settings_status.is_empty() {
            let status_text = format!("状态: {}", self.settings_status);
            let status_line =
                truncate_for_width(&self.ui_font, &status_text, Display::width() - 48);
            self.display.draw_text_font(
                &self.ui_font,
                &status_line,
                LIST_X,
                Display::height() - self.ui_font.glyph_height as usize - PAGE_PATH_Y_OFFSET,
            );
        }
    }

    fn render_current_file(&mut self) {
        self.display.clear(0xFF);

        if self.md_files.is_empty() {
            self.display.draw_text_wrapped(
                &self.ui_font,
                "没有 Markdown 文件\n/sdcard/vault",
                24,
                20,
                Display::width() - 24,
                4,
            );
            debug!("No files to render");
            return;
        }

        let reader = match &self.activity {
            Activity::Reader(reader) => Some(*reader),
            _ => None,
        };

        let file_index = match self.activity {
            Activity::Reader(reader) => reader.file_index.min(self.md_files.len() - 1),
            _ => 0,
        };
        let rel_path = self.md_files[file_index].clone();
        match self.ensure_reader_cache(file_index) {
            Ok(()) => {
                let page_count = self.reader_page_count().max(1);
                let page_index = reader
                    .map(|reader| reader.page_index.min(page_count - 1))
                    .unwrap_or(0);
                if let Some(reader) = reader {
                    if page_index != reader.page_index {
                        self.activity = Activity::Reader(ReaderState {
                            file_index,
                            page_index,
                        });
                    }
                }

                let fonts = FontSet::new(
                    &self.ui_font,
                    &self.reader_font,
                    &self.math_font,
                    &self.script_font,
                );
                if let Some(cache) = self.reader_cache.as_mut() {
                    cache.ensure_window(page_index, &fonts);
                }

                let (_, name) = file_browser_parts(&rel_path);
                let title = format!("[{}] {}", file_index + 1, name);
                let title = truncate_for_width(&self.ui_font, &title, Display::width() - 48);
                self.display
                    .draw_text_font(&self.ui_font, &title, READER_X, 10);
                self.display
                    .fill_rect(READER_X, 34, Display::width() - 48, 1, 0x00);

                let cache = self
                    .reader_cache
                    .as_ref()
                    .filter(|c| c.file_index == file_index);
                if let Some(page) = cache.and_then(|c| c.get_page(page_index)) {
                    draw_reader_page(&mut self.display, &fonts, page, |image_path| {
                        self.hardware
                            .storage
                            .resolve_asset_path_relative_to(&rel_path, image_path)
                    });
                }
                let footer = format!("{}/{}", page_index + 1, page_count);
                let footer_x =
                    Display::width().saturating_sub(READER_X + self.ui_font.text_width(&footer));
                self.display.draw_text_font(
                    &self.ui_font,
                    &footer,
                    footer_x,
                    Display::height() - self.ui_font.glyph_height as usize - 8,
                );
                debug!(
                    "Rendering file {}/{} page {}/{}: {}",
                    file_index + 1,
                    self.md_files.len(),
                    page_index + 1,
                    page_count,
                    rel_path
                );
            }
            Err(e) => {
                self.display.draw_text_wrapped(
                    &self.ui_font,
                    &format!("Error reading {}:\n{}", rel_path, e),
                    24,
                    20,
                    Display::width() - 24,
                    4,
                );
                warn!("Failed to read {}: {}", rel_path, e);
            }
        }
    }

    fn ensure_reader_cache(&mut self, file_index: usize) -> Result<()> {
        if matches!(
            self.reader_cache,
            Some(ReaderCache {
                file_index: cached,
                ..
            }) if cached == file_index
        ) {
            return Ok(());
        }

        // Free heap before heavy markdown parsing
        self.reader_cache = None;
        self.display.clear_glyph_cache();

        #[cfg(debug_assertions)]
        {
            let free_before = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() };
            info!("Free heap before parsing: {} bytes", free_before);
        }

        let rel_path = &self.md_files[file_index];
        let markdown = self.hardware.storage.read_markdown_file(rel_path)?;
        let fonts = FontSet::new(
            &self.ui_font,
            &self.reader_font,
            &self.math_font,
            &self.script_font,
        );

        // Parse blocks and paginate. We keep blocks for re-pagination and
        // only cache a sliding window of rendered pages to save RAM.
        let (mut blocks, all_pages) = markdown_blocks_and_pages(&markdown, &fonts);

        // Compact parsed markdown structures to reduce long-lived heap.
        for block in &mut blocks {
            block.text.shrink_to_fit();
            block.prefix.shrink_to_fit();
            if let Some(image) = block.image.as_mut() {
                image.path.shrink_to_fit();
                image.alt.shrink_to_fit();
            }
        }
        blocks.shrink_to_fit();

        let page_count = all_pages.len().max(1);
        let window_len = self.select_reader_window_len();
        let keep_all_pages = self.should_keep_all_pages(page_count);

        // Build cache with first window of pages
        let mut page_window: Vec<(usize, Option<ReaderPage>)> =
            Vec::with_capacity(window_len.max(PAGE_CACHE_SIZE_MIN));
        page_window.resize_with(window_len.max(PAGE_CACHE_SIZE_MIN), || (0, None));

        let window_end = window_len.min(page_count);
        for (i, page) in all_pages.iter().cloned().enumerate().take(window_end) {
            if i < window_len {
                page_window[i] = (i, Some(page));
            }
        }

        self.reader_cache = Some(ReaderCache {
            file_index,
            blocks,
            page_count,
            all_pages: if keep_all_pages {
                Some(all_pages)
            } else {
                None
            },
            page_window,
            window_len,
            window_cursor: crate::reader::PaginationCursor::default(),
        });

        // Drop the markdown string (blocks own their text now)
        drop(markdown);

        #[cfg(debug_assertions)]
        {
            let free_after = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() };
            let min_free = unsafe { esp_idf_hal::sys::esp_get_minimum_free_heap_size() };
            info!(
                "Free heap after parsing: {} bytes (min ever: {})",
                free_after, min_free
            );
        }

        Ok(())
    }

    fn select_reader_window_len(&self) -> usize {
        let free_heap = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() } as usize;
        if free_heap >= 120 * 1024 {
            PAGE_CACHE_SIZE_MAX
        } else {
            PAGE_CACHE_SIZE_MIN
        }
    }

    fn should_keep_all_pages(&self, page_count: usize) -> bool {
        let free_heap = unsafe { esp_idf_hal::sys::esp_get_free_heap_size() } as usize;
        // Conservative rule: keep full pages only for small/medium files when heap is healthy.
        free_heap >= 150 * 1024 && page_count <= 120
    }

    fn reader_page_count(&self) -> usize {
        self.reader_cache
            .as_ref()
            .map(|cache| cache.page_count)
            .unwrap_or(0)
    }

    fn browser_row_count(&self) -> usize {
        let row_height = self.browser_row_height();
        (Display::height() - LIST_TOP_Y - LIST_BOTTOM_MARGIN) / row_height
    }

    fn browser_row_height(&self) -> usize {
        self.ui_font.glyph_height as usize + 12
    }

    pub fn loop_delay_ms(&self) -> u32 {
        if self.event_pump.idle_ticks() > 500 {
            IDLE_LOOP_DELAY_MS
        } else {
            DEFAULT_LOOP_DELAY_MS
        }
    }
}

fn draw_boot_screen(display: &mut Display, ui_font: &Font, _md_count: usize) {
    info!("Drawing boot screen");
    display.clear(0xFF);

    let text = "你好，世界。";
    let text_w = ui_font.text_width(text);
    let text_h = ui_font.glyph_height as usize;
    let x = (Display::width().saturating_sub(text_w)) / 2;
    let y = (Display::height().saturating_sub(text_h)) / 2;

    display.draw_text_font(ui_font, text, x, y);
}
