[build]
target = "riscv32imc-esp-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[env]
ESP_IDF_VERSION = "v5.3.3"
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
MCU = "esp32c3"
