use crate::display::{Display, RefreshMode};
use crate::font::Font;
use crate::hardware::Hardware;
use crate::input::Button;
use crate::power::PowerManager;
use anyhow::Result;
use log::info;

const DEFAULT_LOOP_DELAY_MS: u32 = 10;
const IDLE_LOOP_DELAY_MS: u32 = 50;

// Generated by tools/generate_font.py
static FONT_16_DATA: &[u8] = include_bytes!("../generated/font_16.bin");

const SAMPLE_TEXT: &str = "\
rr_reader 电子书阅读器

中文渲染测试
这是一段用于测试中文字体渲染效果的示例文本。本项目基于ESP32-C3平台，
使用Rust语言开发，目标是为Xteink X4电子墨水屏设备提供一个高效的
固件解决方案。

SSD1677 电子墨水屏支持三种刷新模式：
- 全刷（Full）：质量最佳，约1600ms
- 半刷（Half）：跳过温度加载，约900ms
- 快刷（Fast）：差分更新，约400-600ms

按钮映射：
前进翻页 → 侧键下
后退翻页 → 侧键上
返回 → 正面左键
确认 → 正面中键

The quick brown fox jumps over the lazy dog.
ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789
";

pub struct ReaderApp {
    hardware: Hardware,
    display: Display,
    font: Font,
    power: PowerManager,
    idle_ticks: u32,
    page: u32,
}

impl ReaderApp {
    pub fn boot(mut hardware: Hardware, mut display: Display) -> Result<Self> {
        info!("Booting rr_reader");

        hardware.mount_storage()?;
        display.begin()?;

        let font = Font::new(FONT_16_DATA)?;
        info!(
            "Font loaded: {}x{}px, {} glyphs",
            font.glyph_width, font.glyph_height, font.glyph_count
        );

        // Show boot screen with font characters
        display.show_boot_screen()?;
        display.draw_text_font(&font, "电子书阅读器", 220, 280);
        display.flush_with_mode(RefreshMode::Full)?;

        info!("Boot complete");

        Ok(Self {
            hardware,
            display,
            font,
            power: PowerManager::new(),
            idle_ticks: 0,
            page: 0,
        })
    }

    pub fn tick(&mut self) -> Result<()> {
        self.hardware.update_inputs();

        let has_activity = self.hardware.has_user_activity();
        if has_activity {
            self.idle_ticks = 0;
            self.power.mark_activity();
        } else {
            self.idle_ticks = self.idle_ticks.saturating_add(1);
            self.power.tick();
        }

        self.handle_input()?;

        // Flush display if dirty
        self.display.flush_if_dirty()?;

        // Auto-sleep
        if self.power.should_sleep() {
            info!("Auto-sleep after {} idle ticks", self.idle_ticks);
            self.power.enter_deep_sleep(None);
        }

        Ok(())
    }

    fn handle_input(&mut self) -> Result<()> {
        use Button::*;

        if self.hardware.input.logical_was_pressed(PageForward) {
            info!("Page forward");
            self.page = self.page.saturating_add(1);
            self.render_page();
        }
        if self.hardware.input.logical_was_pressed(PageBack) {
            info!("Page back");
            self.page = self.page.saturating_sub(1);
            self.render_page();
        }

        // Confirm button: toggle between boot screen and test page
        if self.hardware.input.logical_was_pressed(Confirm) {
            info!("Confirm pressed — rendering test page");
            self.render_page();
        }

        // Power button long press → sleep
        if self.hardware.input.is_pressed(crate::input::BTN_POWER)
            && self.hardware.input.held_ms(crate::input::BTN_POWER) >= 2000
        {
            info!("Power long press → sleep");
            self.power.enter_deep_sleep(None);
        }

        Ok(())
    }

    fn render_page(&mut self) {
        self.display.clear(0xFF);
        self.display.draw_text_wrapped(
            &self.font,
            SAMPLE_TEXT,
            20,
            20,
            Display::width() - 20,
            4,
        );
        info!("Page {} rendered", self.page);
    }

    pub fn loop_delay_ms(&self) -> u32 {
        if self.idle_ticks > 500 {
            IDLE_LOOP_DELAY_MS
        } else {
            DEFAULT_LOOP_DELAY_MS
        }
    }
}
