use crate::display::{Display, RefreshMode};
use crate::font::Font;
use crate::hardware::Hardware;
use crate::input::Button;
use crate::power::PowerManager;
use anyhow::Result;
use esp_idf_hal::sys;
use log::{info, warn};

const DEFAULT_LOOP_DELAY_MS: u32 = 10;
const IDLE_LOOP_DELAY_MS: u32 = 50;
const LIST_TOP_Y: usize = 54;
const LIST_BOTTOM_MARGIN: usize = 22;
const LIST_X: usize = 20;
const LIST_RIGHT_MARGIN: usize = 20;
const READER_TEXT_Y: usize = 38;
const INPUT_STARTUP_IGNORE_MS: u64 = 300;
const BROWSER_CONTINUOUS_START_MS: u32 = 500;
const BROWSER_CONTINUOUS_INTERVAL_MS: u64 = 500;

// Generated by tools/generate_font.py
static FONT_16_DATA: &[u8] = include_bytes!("../generated/font_16.bin");

#[derive(Clone, Debug)]
enum Activity {
    FileBrowser(FileBrowserState),
    Reader(ReaderState),
}

#[derive(Clone, Debug)]
struct FileBrowserState {
    selected: usize,
    first_visible: usize,
}

#[derive(Clone, Debug)]
struct ReaderState {
    file_index: usize,
}

pub struct ReaderApp {
    hardware: Hardware,
    display: Display,
    font: Font,
    power: PowerManager,
    idle_ticks: u32,
    md_files: Vec<String>,
    activity: Activity,
    input_ignore_until_ms: u64,
    browser_last_continuous_nav_ms: u64,
    browser_continuous_nav: bool,
}

impl ReaderApp {
    pub fn boot(mut hardware: Hardware, mut display: Display) -> Result<Self> {
        info!("Booting rr_reader");

        hardware.mount_storage()?;
        display.begin()?;

        let font = Font::new(FONT_16_DATA)?;
        info!(
            "Font loaded: {}x{}px, {} glyphs",
            font.glyph_width, font.glyph_height, font.glyph_count
        );

        // Scan vault for markdown files
        let mut md_files = match hardware.storage.list_markdown_files("") {
            Ok(files) => files,
            Err(e) => {
                warn!("Failed to scan vault: {}", e);
                Vec::new()
            }
        };
        md_files.sort();
        info!("Found {} markdown files in vault", md_files.len());

        // Show boot screen with status
        display.show_boot_screen()?;
        display.draw_text_font(&font, &format!("文件: {}", md_files.len()), 220, 280);
        display.flush_with_mode(RefreshMode::Full)?;

        info!("Boot complete");

        let mut app = Self {
            hardware,
            display,
            font,
            power: PowerManager::new(),
            idle_ticks: 0,
            md_files,
            activity: Activity::FileBrowser(FileBrowserState {
                selected: 0,
                first_visible: 0,
            }),
            input_ignore_until_ms: now_ms() + INPUT_STARTUP_IGNORE_MS,
            browser_last_continuous_nav_ms: 0,
            browser_continuous_nav: false,
        };
        app.render_current_activity();
        app.flush_ui_refresh();
        Ok(app)
    }

    pub fn tick(&mut self) -> Result<()> {
        self.hardware.update_inputs();

        let has_activity = self.hardware.has_user_activity();
        if has_activity {
            self.idle_ticks = 0;
            self.power.mark_activity();
        } else {
            self.idle_ticks = self.idle_ticks.saturating_add(1);
            self.power.tick();
        }

        if now_ms() < self.input_ignore_until_ms {
            self.display.flush_if_dirty()?;
            return Ok(());
        }

        self.handle_input()?;

        // Flush display if dirty
        self.display.flush_if_dirty()?;

        // Auto-sleep
        if self.power.should_sleep() {
            info!("Auto-sleep after {} idle ticks", self.idle_ticks);
            self.power.enter_deep_sleep(None);
        }

        Ok(())
    }

    fn handle_input(&mut self) -> Result<()> {
        use Button::*;

        match self.activity.clone() {
            Activity::FileBrowser(_) => {
                let next_buttons = [Down, Right];
                let previous_buttons = [Up, Left];

                if self.should_navigate_browser_continuously(&next_buttons) {
                    self.move_browser_page(1);
                    self.mark_browser_continuous_nav();
                }

                if self.should_navigate_browser_continuously(&previous_buttons) {
                    self.move_browser_page(-1);
                    self.mark_browser_continuous_nav();
                }

                if self.hardware.input.any_logical_pressed(&next_buttons) {
                    self.move_browser_selection(1);
                    self.reset_browser_continuous_nav();
                } else if self.hardware.input.any_logical_released(&next_buttons) {
                    self.reset_browser_continuous_nav();
                }

                if self.hardware.input.any_logical_pressed(&previous_buttons) {
                    self.move_browser_selection(-1);
                    self.reset_browser_continuous_nav();
                } else if self.hardware.input.any_logical_released(&previous_buttons) {
                    self.reset_browser_continuous_nav();
                }

                if self.hardware.input.logical_was_pressed(Confirm) {
                    self.open_selected_file();
                }
            }
            Activity::Reader(reader) => {
                if self.hardware.input.any_logical_pressed(&[Back, Left]) {
                    self.activity = Activity::FileBrowser(FileBrowserState {
                        selected: reader.file_index,
                        first_visible: self.browser_first_visible_for(reader.file_index),
                    });
                    self.render_file_browser();
                    self.flush_ui_refresh();
                }

                if self.hardware.input.logical_was_pressed(PageForward) {
                    self.open_adjacent_file(1);
                }

                if self.hardware.input.logical_was_pressed(PageBack) {
                    self.open_adjacent_file(-1);
                }

                if self.hardware.input.logical_was_pressed(Confirm) {
                    self.render_current_file();
                    self.flush_ui_refresh();
                }
            }
        }

        // Power button long press → sleep
        if self.hardware.input.is_pressed(crate::input::BTN_POWER)
            && self.hardware.input.held_ms(crate::input::BTN_POWER) >= 2000
        {
            info!("Power long press → sleep");
            self.power.enter_deep_sleep(None);
        }

        Ok(())
    }

    fn render_current_activity(&mut self) {
        match self.activity {
            Activity::FileBrowser(_) => self.render_file_browser(),
            Activity::Reader(_) => self.render_current_file(),
        }
    }

    fn move_browser_selection(&mut self, delta: isize) {
        if self.md_files.is_empty() {
            return;
        }

        let file_count = self.md_files.len();
        let selected = match &self.activity {
            Activity::FileBrowser(browser) => browser.selected,
            _ => return,
        };
        let next = (selected as isize + delta).rem_euclid(file_count as isize) as usize;
        self.set_browser_selection(next);
        self.render_file_browser();
        self.flush_ui_refresh();
    }

    fn move_browser_page(&mut self, delta: isize) {
        if self.md_files.is_empty() {
            return;
        }

        let row_count = self.browser_row_count().max(1);
        let file_count = self.md_files.len();
        if file_count <= row_count {
            self.move_browser_selection(delta.signum());
            return;
        }

        let selected = match &self.activity {
            Activity::FileBrowser(browser) => browser.selected,
            _ => return,
        };
        let current_page = selected / row_count;
        let last_page = (file_count - 1) / row_count;
        let next = if delta.is_negative() {
            if current_page > 0 {
                (current_page - 1) * row_count
            } else {
                last_page * row_count
            }
        } else if current_page < last_page {
            (current_page + 1) * row_count
        } else {
            0
        };

        self.set_browser_selection(next.min(file_count - 1));
        self.render_file_browser();
        self.flush_ui_refresh();
    }

    fn set_browser_selection(&mut self, selected: usize) {
        let row_count = self.browser_row_count().max(1);

        if let Activity::FileBrowser(browser) = &mut self.activity {
            browser.selected = selected;
            if browser.selected < browser.first_visible {
                browser.first_visible = browser.selected;
            } else if browser.selected >= browser.first_visible + row_count {
                browser.first_visible = browser.selected + 1 - row_count;
            }
        }
    }

    fn should_navigate_browser_continuously(&self, buttons: &[Button]) -> bool {
        if !buttons
            .iter()
            .any(|&button| self.hardware.input.logical_is_pressed(button))
        {
            return false;
        }

        let held_long_enough =
            self.hardware.input.held_ms(crate::input::BTN_DOWN) > BROWSER_CONTINUOUS_START_MS;
        let interval_elapsed = now_ms().saturating_sub(self.browser_last_continuous_nav_ms)
            > BROWSER_CONTINUOUS_INTERVAL_MS;

        held_long_enough && interval_elapsed
    }

    fn mark_browser_continuous_nav(&mut self) {
        self.browser_continuous_nav = true;
        self.browser_last_continuous_nav_ms = now_ms();
    }

    fn reset_browser_continuous_nav(&mut self) {
        self.browser_continuous_nav = false;
        self.browser_last_continuous_nav_ms = 0;
    }

    fn open_selected_file(&mut self) {
        let file_index = match &self.activity {
            Activity::FileBrowser(browser) if !self.md_files.is_empty() => browser.selected,
            _ => return,
        };

        self.activity = Activity::Reader(ReaderState { file_index });
        self.render_current_file();
        self.flush_ui_refresh();
    }

    fn open_adjacent_file(&mut self, delta: isize) {
        if self.md_files.is_empty() {
            return;
        }

        let current = match &self.activity {
            Activity::Reader(reader) => reader.file_index,
            _ => return,
        };

        let next = if delta.is_negative() {
            current
                .checked_sub(delta.unsigned_abs().min(current))
                .unwrap_or(0)
        } else {
            current
                .saturating_add(delta as usize)
                .min(self.md_files.len() - 1)
        };

        self.activity = Activity::Reader(ReaderState { file_index: next });
        self.render_current_file();
        self.flush_ui_refresh();
    }

    fn flush_ui_refresh(&mut self) {
        if let Err(e) = self.display.flush_with_mode(RefreshMode::Half) {
            warn!("UI refresh failed: {}", e);
        }
    }

    fn render_file_browser(&mut self) {
        self.display.clear(0xFF);

        self.display
            .draw_text_font(&self.font, "rr_reader / vault", 20, 12);

        if self.md_files.is_empty() {
            self.display.draw_text_wrapped(
                &self.font,
                "No markdown files found.\n\nPlace .md files under /sdcard/vault/",
                20,
                LIST_TOP_Y,
                Display::width() - 20,
                4,
            );
            info!("Rendering empty file browser");
            return;
        }

        let (selected, first_visible) = match &self.activity {
            Activity::FileBrowser(browser) => (browser.selected, browser.first_visible),
            Activity::Reader(reader) => (
                reader.file_index,
                self.browser_first_visible_for(reader.file_index),
            ),
        };

        let row_height = self.font.glyph_height as usize + 4;
        let row_count = self.browser_row_count();
        let end = (first_visible + row_count).min(self.md_files.len());
        let summary = format!(
            "{} / {} files  {}-{}",
            selected + 1,
            self.md_files.len(),
            first_visible + 1,
            end
        );
        self.display.draw_text_font(&self.font, &summary, 20, 32);

        for (row, idx) in (first_visible..end).enumerate() {
            let marker = if idx == selected { ">" } else { " " };
            let prefix = format!("{} {:03} ", marker, idx + 1);
            let prefix_width = prefix.chars().count() * self.font.glyph_width as usize;
            let path = Self::truncate_for_width(
                &self.md_files[idx],
                Display::width() - LIST_X - LIST_RIGHT_MARGIN - prefix_width,
                self.font.glyph_width as usize,
            );
            let line = format!("{}{}", prefix, path);
            self.display
                .draw_text_font(&self.font, &line, LIST_X, LIST_TOP_Y + row * row_height);
        }

        let footer = match (first_visible > 0, end < self.md_files.len()) {
            (true, true) => "^ more / v more",
            (true, false) => "^ more",
            (false, true) => "v more",
            (false, false) => "",
        };
        if !footer.is_empty() {
            self.display.draw_text_font(
                &self.font,
                footer,
                20,
                Display::height() - self.font.glyph_height as usize - 4,
            );
        }

        info!(
            "Rendering file browser: selected {}/{}",
            selected + 1,
            self.md_files.len()
        );
    }

    fn render_current_file(&mut self) {
        self.display.clear(0xFF);

        if self.md_files.is_empty() {
            self.display.draw_text_wrapped(
                &self.font,
                "No markdown files found.\n\nPlace .md files under /sdcard/vault/",
                20,
                20,
                Display::width() - 20,
                4,
            );
            info!("No files to render");
            return;
        }

        let file_index = match &self.activity {
            Activity::Reader(reader) => reader.file_index.min(self.md_files.len() - 1),
            Activity::FileBrowser(browser) => browser.selected.min(self.md_files.len() - 1),
        };
        let rel_path = &self.md_files[file_index];
        match self.hardware.storage.read_markdown_file(rel_path) {
            Ok(content) => {
                let title = format!("[{}] {}", file_index + 1, rel_path);
                self.display.draw_text_font(&self.font, &title, 20, 10);
                self.display.draw_text_wrapped(
                    &self.font,
                    &content,
                    20,
                    READER_TEXT_Y,
                    Display::width() - 20,
                    4,
                );
                info!(
                    "Rendering file {}/{}: {}",
                    file_index + 1,
                    self.md_files.len(),
                    rel_path
                );
            }
            Err(e) => {
                self.display.draw_text_wrapped(
                    &self.font,
                    &format!("Error reading {}:\n{}", rel_path, e),
                    20,
                    20,
                    Display::width() - 20,
                    4,
                );
                warn!("Failed to read {}: {}", rel_path, e);
            }
        }
    }

    fn browser_row_count(&self) -> usize {
        let row_height = self.font.glyph_height as usize + 4;
        (Display::height() - LIST_TOP_Y - LIST_BOTTOM_MARGIN) / row_height
    }

    fn browser_first_visible_for(&self, selected: usize) -> usize {
        let row_count = self.browser_row_count().max(1);
        selected.saturating_sub(row_count / 2)
    }

    fn truncate_for_width(text: &str, max_px: usize, glyph_width: usize) -> String {
        let max_chars = (max_px / glyph_width).max(1);
        let char_count = text.chars().count();
        if char_count <= max_chars {
            return text.to_string();
        }

        if max_chars <= 3 {
            return ".".repeat(max_chars);
        }

        let mut truncated = text.chars().take(max_chars - 3).collect::<String>();
        truncated.push_str("...");
        truncated
    }

    pub fn loop_delay_ms(&self) -> u32 {
        if self.idle_ticks > 500 {
            IDLE_LOOP_DELAY_MS
        } else {
            DEFAULT_LOOP_DELAY_MS
        }
    }
}

fn now_ms() -> u64 {
    unsafe { (sys::esp_timer_get_time() / 1000) as u64 }
}
