// Compressed bitmap font for CJK text rendering.
//
// Font binary format (generated by tools/generate_font.py):
//   [0..4]   magic: b"FNT2"
//   [4]      glyph_width: u8
//   [5]      glyph_height: u8
//   [6..8]   glyph_count: u16 LE
//   [8..]    index: glyph_count × 16 bytes (codepoint:u32, offset:u32,
//            compressed_size:u16, uncompressed_size:u16, advance:u8,
//            reserved:3 — numeric fields LE)
//   [...data blob...]

use anyhow::{anyhow, Result};
use flate2::read::ZlibDecoder;
use std::io::Read;

const MAGIC: &[u8; 4] = b"FNT2";
const INDEX_ENTRY_SIZE: usize = 16;

pub struct Font {
    data: &'static [u8],
    pub glyph_width: u8,
    pub glyph_height: u8,
    pub glyph_count: u16,
    /// Bytes per glyph row (padded to byte boundary)
    pub row_bytes: u8,
    /// Total uncompressed bytes per glyph
    pub glyph_bytes: u16,
}

pub struct GlyphInfo {
    data_offset: usize,
    compressed_size: usize,
    uncompressed_size: usize,
    advance_width: usize,
}

impl Font {
    /// Parse a font from a static binary blob. The data must live for `'static`
    /// (typically via `include_bytes!`).
    pub fn new(data: &'static [u8]) -> Result<Self> {
        if data.len() < 8 {
            return Err(anyhow!("Font data too short for header"));
        }
        if &data[0..4] != MAGIC.as_slice() {
            return Err(anyhow!("Invalid font magic bytes"));
        }

        let glyph_width = data[4];
        let glyph_height = data[5];
        let glyph_count = u16::from_le_bytes([data[6], data[7]]);
        let row_bytes = glyph_width.div_ceil(8);
        let glyph_bytes = row_bytes as u16 * glyph_height as u16;

        let min_len = 8 + glyph_count as usize * INDEX_ENTRY_SIZE;
        if data.len() < min_len {
            return Err(anyhow!(
                "Font data too short for index: {} glyphs, need {} bytes, got {}",
                glyph_count,
                min_len,
                data.len()
            ));
        }

        Ok(Self {
            data,
            glyph_width,
            glyph_height,
            glyph_count,
            row_bytes,
            glyph_bytes,
        })
    }

    /// Binary search for a glyph by Unicode codepoint. Returns None for
    /// unsupported characters (render as space or replacement glyph).
    pub fn find_glyph(&self, codepoint: u32) -> Option<GlyphInfo> {
        let index_start = 8;
        let index_end = index_start + self.glyph_count as usize * INDEX_ENTRY_SIZE;
        let index = &self.data[index_start..index_end];

        let mut lo: usize = 0;
        let mut hi = self.glyph_count as usize;
        while lo < hi {
            let mid = (lo + hi) / 2;
            let entry = &index[mid * INDEX_ENTRY_SIZE..][..INDEX_ENTRY_SIZE];
            let cp = u32::from_le_bytes([entry[0], entry[1], entry[2], entry[3]]);
            if cp < codepoint {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if lo >= self.glyph_count as usize {
            return None;
        }

        let entry = &index[lo * INDEX_ENTRY_SIZE..][..INDEX_ENTRY_SIZE];
        let cp = u32::from_le_bytes([entry[0], entry[1], entry[2], entry[3]]);
        if cp != codepoint {
            return None;
        }

        let data_offset = u32::from_le_bytes([entry[4], entry[5], entry[6], entry[7]]) as usize;
        let compressed_size = u16::from_le_bytes([entry[8], entry[9]]) as usize;
        let uncompressed_size = u16::from_le_bytes([entry[10], entry[11]]) as usize;
        let advance_width = entry[12] as usize;

        Some(GlyphInfo {
            data_offset,
            compressed_size,
            uncompressed_size,
            advance_width,
        })
    }

    /// Decompress a glyph bitmap into `buf`. The buffer must be at least
    /// `self.glyph_bytes` bytes.
    pub fn decompress_glyph(&self, info: &GlyphInfo, buf: &mut [u8]) -> Result<()> {
        let compressed = &self.data[info.data_offset..][..info.compressed_size];
        let mut decoder = ZlibDecoder::new(compressed);
        decoder.read_exact(&mut buf[..info.uncompressed_size])?;
        Ok(())
    }

    pub fn char_advance_width(&self, ch: char) -> usize {
        if ch == '\t' {
            return self.glyph_width as usize * 2;
        }

        if let Some(info) = self.find_glyph(ch as u32) {
            return info.advance_width.max(1);
        }

        self.fallback_advance_width(ch as u32)
    }

    fn fallback_advance_width(&self, codepoint: u32) -> usize {
        let full = self.glyph_width as usize;
        if codepoint == b' ' as u32 {
            (full / 2).max(1)
        } else if is_halfwidth_codepoint(codepoint) {
            (full * 5 / 8).max(1)
        } else {
            full
        }
    }

    pub fn text_width(&self, text: &str) -> usize {
        text.chars().map(|ch| self.char_advance_width(ch)).sum()
    }

    /// Render a decompressed glyph bitmap to the framebuffer at (x, y).
    /// Pixels outside the display bounds are clipped.
    pub fn draw_glyph(
        &self,
        bitmap: &[u8],
        x: usize,
        y: usize,
        fb_width: usize,
        fb_height: usize,
        fb: &mut [u8],
    ) {
        let fb_row_bytes = fb_width.div_ceil(8);
        for row in 0..self.glyph_height as usize {
            let screen_y = y + row;
            if screen_y >= fb_height {
                break;
            }
            for col in 0..self.glyph_width as usize {
                let screen_x = x + col;
                if screen_x >= fb_width {
                    break;
                }
                let byte_idx = row * self.row_bytes as usize + col / 8;
                let bit = (bitmap[byte_idx] >> (7 - col % 8)) & 1;
                if bit != 0 {
                    let fb_idx = screen_y * fb_row_bytes + screen_x / 8;
                    fb[fb_idx] &= !(0x80 >> (screen_x % 8));
                }
            }
        }
    }
}

fn is_halfwidth_codepoint(codepoint: u32) -> bool {
    matches!(
        codepoint,
        0x0000..=0x00FF
            | 0x0100..=0x024F
            | 0x1E00..=0x1EFF
            | 0xFF61..=0xFFDC
            | 0xFFE8..=0xFFEE
    )
}

// ── UTF-8 iteration ────────────────────────────────────────────────

/// Yields (codepoint, byte_offset) pairs from a UTF-8 string slice.
pub fn utf8_codepoints(s: &str) -> impl Iterator<Item = (u32, usize)> + '_ {
    s.char_indices().map(|(i, c)| (c as u32, i))
}

// ── Text layout ────────────────────────────────────────────────────

/// Render a UTF-8 string with the given font at (x, y). Wraps lines at
/// `max_x` (in pixels). Returns the y coordinate of the next line.
/// `line_spacing` is extra pixels between lines (added to glyph height).
/// Characters not found in the font are silently skipped (treated as space).
pub struct TextWrapTarget<'a> {
    pub x: usize,
    pub y: usize,
    pub max_x: usize,
    pub fb_width: usize,
    pub fb_height: usize,
    pub line_spacing: usize,
    pub fb: &'a mut [u8],
}

pub fn draw_text_wrapped(font: &Font, text: &str, target: TextWrapTarget<'_>) -> usize {
    let mut x = target.x;
    let mut y = target.y;
    let start_x = x;
    let mut decompress_buf = vec![0u8; font.glyph_bytes as usize];

    for ch in text.chars() {
        let cp = ch as u32;

        // Handle newlines
        if cp == b'\n' as u32 {
            x = start_x;
            y += font.glyph_height as usize + target.line_spacing;
            continue;
        }

        // Word-wrap: if the next glyph would overflow, advance to next line
        let advance = font.char_advance_width(ch);
        if x + advance > target.max_x {
            x = start_x;
            y += font.glyph_height as usize + target.line_spacing;
        }

        if y + font.glyph_height as usize > target.fb_height {
            break; // off screen
        }

        // Skip spaces (no glyph to draw)
        if cp == b' ' as u32 {
            x += advance;
            continue;
        }

        if let Some(info) = font.find_glyph(cp) {
            if font.decompress_glyph(&info, &mut decompress_buf).is_ok() {
                font.draw_glyph(
                    &decompress_buf,
                    x,
                    y,
                    target.fb_width,
                    target.fb_height,
                    target.fb,
                );
            }
        }
        // Glyph not found → skip (advance cursor anyway)
        x += advance;
    }

    y + font.glyph_height as usize + target.line_spacing
}
