// Compressed bitmap font for CJK text rendering.
//
// Font binary format (generated by tools/generate_font.py):
//   [0..4]   magic: b"FNT2"
//   [4]      glyph_width: u8
//   [5]      glyph_height: u8
//   [6..8]   glyph_count: u16 LE
//   [8..]    index: glyph_count × 16 bytes (codepoint:u32, offset:u32,
//            compressed_size:u16, uncompressed_size:u16, advance:u8,
//            baseline:u8, reserved:2 — numeric fields LE)
//   [...data blob...]

use anyhow::{anyhow, Result};
use flate2::{Decompress, FlushDecompress};

const MAGIC: &[u8; 4] = b"FNT2";
const INDEX_ENTRY_SIZE: usize = 16;

pub struct Font {
    data: &'static [u8],
    pub glyph_width: u8,
    pub glyph_height: u8,
    pub glyph_count: u16,
    /// Bytes per glyph row (padded to byte boundary)
    pub row_bytes: u8,
}

#[derive(Clone, Copy)]
pub struct FontSet<'a> {
    pub ui: &'a Font,
    pub reader: &'a Font,
    pub math: &'a Font,
    pub script: &'a Font,
}

impl<'a> FontSet<'a> {
    pub fn new(ui: &'a Font, reader: &'a Font, math: &'a Font, script: &'a Font) -> Self {
        Self {
            ui,
            reader,
            math,
            script,
        }
    }
}

pub struct GlyphInfo {
    data_offset: usize,
    compressed_size: usize,
    uncompressed_size: usize,
    advance_width: usize,
    /// Distance from top of glyph cell to the font baseline (pixels).
    /// Zero for fonts generated before this field was added; callers
    /// should fall back to `glyph_height * 3/4` in that case.
    pub baseline: usize,
}

impl Font {
    /// Parse a font from a static binary blob. The data must live for `'static`
    /// (typically via `include_bytes!`).
    pub fn new(data: &'static [u8]) -> Result<Self> {
        if data.len() < 8 {
            return Err(anyhow!("Font data too short for header"));
        }
        if &data[0..4] != MAGIC.as_slice() {
            return Err(anyhow!("Invalid font magic bytes"));
        }

        let glyph_width = data[4];
        let glyph_height = data[5];
        let glyph_count = u16::from_le_bytes([data[6], data[7]]);
        let row_bytes = glyph_width.div_ceil(8);

        let min_len = 8 + glyph_count as usize * INDEX_ENTRY_SIZE;
        if data.len() < min_len {
            return Err(anyhow!(
                "Font data too short for index: {} glyphs, need {} bytes, got {}",
                glyph_count,
                min_len,
                data.len()
            ));
        }

        Ok(Self {
            data,
            glyph_width,
            glyph_height,
            glyph_count,
            row_bytes,
        })
    }

    pub fn id(&self) -> usize {
        self.data.as_ptr() as usize
    }

    /// Binary search for a glyph by Unicode codepoint. Returns None for
    /// unsupported characters (render as space or replacement glyph).
    pub fn find_glyph(&self, codepoint: u32) -> Option<GlyphInfo> {
        let index_start = 8;
        let index_end = index_start + self.glyph_count as usize * INDEX_ENTRY_SIZE;
        let index = &self.data[index_start..index_end];

        let mut lo: usize = 0;
        let mut hi = self.glyph_count as usize;
        while lo < hi {
            let mid = (lo + hi) / 2;
            let entry = &index[mid * INDEX_ENTRY_SIZE..][..INDEX_ENTRY_SIZE];
            let cp = u32::from_le_bytes([entry[0], entry[1], entry[2], entry[3]]);
            if cp < codepoint {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if lo >= self.glyph_count as usize {
            return None;
        }

        let entry = &index[lo * INDEX_ENTRY_SIZE..][..INDEX_ENTRY_SIZE];
        let cp = u32::from_le_bytes([entry[0], entry[1], entry[2], entry[3]]);
        if cp != codepoint {
            return None;
        }

        let data_offset = u32::from_le_bytes([entry[4], entry[5], entry[6], entry[7]]) as usize;
        let compressed_size = u16::from_le_bytes([entry[8], entry[9]]) as usize;
        let uncompressed_size = u16::from_le_bytes([entry[10], entry[11]]) as usize;
        let advance_width = entry[12] as usize;
        let baseline = entry[13] as usize;

        Some(GlyphInfo {
            data_offset,
            compressed_size,
            uncompressed_size,
            advance_width,
            baseline,
        })
    }

    /// Decompress a glyph bitmap into `buf`. The buffer must be at least
    /// `self.glyph_bytes` bytes. `decomp` is a reusable zlib decompressor
    /// (avoids allocating a 32+ KB window per glyph).
    pub fn decompress_glyph(
        &self,
        decomp: &mut Decompress,
        info: &GlyphInfo,
        buf: &mut [u8],
    ) -> Result<()> {
        let compressed_end = info.data_offset.saturating_add(info.compressed_size);
        if compressed_end > self.data.len() || info.uncompressed_size > buf.len() {
            return Err(anyhow!(
                "Invalid glyph bounds: offset={}, compressed={}, uncompressed={}",
                info.data_offset,
                info.compressed_size,
                info.uncompressed_size
            ));
        }

        let compressed = &self.data[info.data_offset..compressed_end];
        decomp.reset(true);
        decomp.decompress(
            compressed,
            &mut buf[..info.uncompressed_size],
            FlushDecompress::Finish,
        )?;
        Ok(())
    }

    pub fn glyph_uncompressed_size(info: &GlyphInfo) -> usize {
        info.uncompressed_size
    }

    pub fn char_advance_width(&self, ch: char) -> usize {
        if ch == '\t' {
            return self.glyph_width as usize * 2;
        }

        if let Some(info) = self.find_glyph(ch as u32) {
            return info.advance_width.max(1);
        }

        self.fallback_advance_width(ch as u32)
    }

    /// Return the baseline distance from top of glyph cell.
    ///
    /// For fonts generated with the updated generator this is read from
    /// the binary; for older fonts it falls back to 3/4 of glyph height.
    pub fn baseline(&self) -> usize {
        // All glyphs in a font share the same baseline.  Look it up from
        // a representative character that every font should have.
        if let Some(info) = self.find_glyph('x' as u32) {
            if info.baseline > 0 {
                return info.baseline;
            }
        }
        self.glyph_height as usize * 3 / 4
    }

    fn fallback_advance_width(&self, codepoint: u32) -> usize {
        let full = self.glyph_width as usize;
        if codepoint == b' ' as u32 {
            (full / 2).max(1)
        } else if is_halfwidth_codepoint(codepoint) {
            (full * 5 / 8).max(1)
        } else {
            full
        }
    }

    pub fn text_width(&self, text: &str) -> usize {
        text.chars().map(|ch| self.char_advance_width(ch)).sum()
    }
}

fn is_halfwidth_codepoint(codepoint: u32) -> bool {
    matches!(
        codepoint,
        0x0000..=0x00FF
            | 0x0100..=0x024F
            | 0x1E00..=0x1EFF
            | 0xFF61..=0xFFDC
            | 0xFFE8..=0xFFEE
    )
}
